package com.kodeboxx.smartintake;

import java.time.*;import java.util.*;import org.springframework.http.*;import org.springframework.jdbc.core.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import com.fasterxml.jackson.databind.*;
import org.springframework.boot.*;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.boot.autoconfigure.*;import org.springframework.context.annotation.*;import org.springframework.web.servlet.config.annotation.*;

@SpringBootApplication public class SmartIntakeApplication {
 public static void main(String[] args){SpringApplication.run(SmartIntakeApplication.class,args);}
 @Bean WebMvcConfigurer cors(){return new WebMvcConfigurer(){public void addCorsMappings(CorsRegistry r){r.addMapping("/v1/**").allowedOrigins("http://localhost:4200").allowedMethods("GET","POST","PUT","PATCH","DELETE");}};}
}
@RestController @RequestMapping("/v1") class Api {
 private final JdbcTemplate db; private final ObjectMapper json;
 Api(JdbcTemplate db,ObjectMapper json){this.db=db;this.json=json;}
 record Bootstrap(String email,String password,String organizationName,String workspaceName){} record CreateForm(String formKey,String title){} record Draft(Map<String,Object> definition){} record StartSession(String locale,String timeZone){} record PatchSession(Long baseRevision,Map<String,Object> answers){} record Submit(Long sessionRevision){}
 @PostMapping("/auth/bootstrap") ResponseEntity<?> bootstrap(@RequestBody Bootstrap in){if(in.email()==null||!in.email().contains("@")||in.password()==null||in.password().length()<12)throw bad("BOOTSTRAP_INVALID","Email and 12+ character password required");if(db.queryForObject("select count(*) from accounts",Integer.class)!=0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Bootstrap closed");UUID a=UUID.randomUUID(),o=UUID.randomUUID(),w=UUID.randomUUID(),t=UUID.randomUUID();db.update("insert into accounts(id,email,password_hash) values(?,?,?)",a,in.email().toLowerCase(),new BCryptPasswordEncoder().encode(in.password()));db.update("insert into organizations(id,name) values(?,?)",o,Optional.ofNullable(in.organizationName()).orElse("Local organization"));db.update("insert into workspaces(id,organization_id,workspace_key,name) values(?,?,?,?)",w,o,"local",Optional.ofNullable(in.workspaceName()).orElse("Local workspace"));db.update("insert into memberships(account_id,workspace_id,role) values(?,?,?)",a,w,"OWNER");db.update("insert into staff_sessions(token,account_id,expires_at) values(?,?,?)",t,a,java.sql.Timestamp.from(Instant.now().plus(Duration.ofHours(8))));audit("BOOTSTRAP_COMPLETED",a);return ResponseEntity.status(201).body(Map.of("staffSession",t.toString(),"workspaceKey","local","roles",List.of("OWNER")));}
 @GetMapping("/health") Map<String,Object> health(){return Map.of("status","UP","service","smart-intake-api","contractVersion","4.0.0");}
 @GetMapping("/capabilities") Map<String,Object> capabilities(){return Map.of("contractVersion","4.0.0","fieldTypes",List.of("text","integer","decimal","boolean","choice","multiChoice","date","object","list","attachments","drawing"),"operators",List.of("equals","notEquals","isAnswered","greaterThan","contains"));}
 @GetMapping("/workspaces/{workspace}/forms") List<Map<String,Object>> forms(@PathVariable String workspace,@RequestHeader(value="X-Staff-Session",required=false) String token){UUID ws=authorize(workspace,token);return db.query("select id,form_key,title,status,revision,updated_at from forms where workspace_id=? order by updated_at desc",(rs,n)->Map.of("id",rs.getObject("id").toString(),"formKey",rs.getString("form_key"),"title",rs.getString("title"),"status",rs.getString("status"),"revision",rs.getLong("revision"),"updatedAt",rs.getObject("updated_at").toString()),ws);}
 @PostMapping("/workspaces/{workspace}/forms") ResponseEntity<?> create(@PathVariable String workspace,@RequestHeader(value="X-Staff-Session",required=false) String token,@RequestBody CreateForm in){UUID ws=authorize(workspace,token);if(in.formKey()==null||!in.formKey().matches("[a-z][a-z0-9-]{2,99}"))throw bad("FORM_KEY_INVALID","Use a lowercase stable key of at least three characters."); UUID id=UUID.randomUUID();Map<String,Object> def=sampleDefinition(in.formKey(),in.title());db.update("insert into forms(id,workspace_id,form_key,title,definition) values(?,?,?,?,cast(? as jsonb))",id,ws,in.formKey(),in.title(),stringify(def));audit("FORM_CREATED",id);return ResponseEntity.status(201).eTag(etag(1)).body(Map.of("id",id,"draftId",id,"revision",1,"definition",def));}
 @GetMapping("/workspaces/{workspace}/forms/{form}/drafts/{draft}") ResponseEntity<?> draft(@PathVariable String workspace,@PathVariable UUID form,@RequestHeader(value="X-Staff-Session",required=false) String token){owned(workspace,token,form);var row=formRow(form);return ResponseEntity.ok().eTag(etag(row.revision())).body(Map.of("id",form,"revision",row.revision(),"definition",parse(row.definition()),"diagnostics",List.of()));}
 @PutMapping("/workspaces/{workspace}/forms/{form}/drafts/{draft}") ResponseEntity<?> save(@PathVariable String workspace,@PathVariable UUID form,@RequestHeader(value="X-Staff-Session",required=false) String token,@RequestHeader(value="If-Match",required=false) String match,@RequestBody Draft in){owned(workspace,token,form);var row=formRow(form);if(match==null)throw new ResponseStatusException(HttpStatus.PRECONDITION_REQUIRED,"If-Match required");if(!match.equals(etag(row.revision())))throw new ResponseStatusException(HttpStatus.PRECONDITION_FAILED,"Draft changed; reload to resolve conflict"); validateDefinition(in.definition());long next=row.revision()+1;db.update("update forms set definition=cast(? as jsonb), revision=?, updated_at=now() where id=?",stringify(in.definition()),next,form);audit("DRAFT_SAVED",form);return ResponseEntity.ok().eTag(etag(next)).body(Map.of("revision",next,"definition",in.definition(),"diagnostics",List.of()));}
 @PostMapping("/workspaces/{workspace}/forms/{form}/releases") ResponseEntity<?> publish(@PathVariable String workspace,@PathVariable UUID form,@RequestHeader(value="X-Staff-Session",required=false) String token){owned(workspace,token,form);var row=formRow(form);validateDefinition(parse(row.definition()));int version=db.queryForObject("select coalesce(max(version),0)+1 from form_releases where form_id=?",Integer.class,form);UUID release=UUID.randomUUID();db.update("insert into form_releases(id,form_id,version,package) values(?,?,?,cast(? as jsonb))",release,form,version,row.definition());db.update("update forms set status='PUBLISHED',updated_at=now() where id=?",form);audit("FORM_PUBLISHED",form);return ResponseEntity.status(201).body(Map.of("releaseId",release,"version",version,"shareId",form.toString(),"status","PUBLISHED"));}
 @PostMapping("/public/forms/{share}/sessions") ResponseEntity<?> start(@PathVariable UUID share,@RequestBody(required=false) StartSession in){R release=latestRelease(share);UUID id=UUID.randomUUID(),secret=UUID.randomUUID();String locale=in==null||in.locale()==null?"en":in.locale();db.update("insert into sessions(id,form_id,release_id,respondent_token,locale,answers) values(?,?,?,?,?,cast('{}' as jsonb))",id,share,release.id(),secret,locale);return ResponseEntity.status(201).body(Map.of("sessionId",id,"respondentSession",secret,"revision",0,"locale",locale,"release",parse(release.pkg()),"expiresAt",Instant.now().plus(Duration.ofDays(7)).toString()));}
 @GetMapping("/sessions/{id}") Map<String,Object> session(@PathVariable UUID id,@RequestHeader(value="X-Respondent-Session",required=false) String token){return sessionView(respondent(id,token));}
 @PatchMapping("/sessions/{id}") Map<String,Object> patch(@PathVariable UUID id,@RequestHeader(value="X-Respondent-Session",required=false) String token,@RequestBody PatchSession in){var s=respondent(id,token);if(!s.status().equals("DRAFT"))throw bad("SESSION_CLOSED","This response has already been submitted.");if(!Objects.equals(in.baseRevision(),s.revision()))throw new ResponseStatusException(HttpStatus.CONFLICT,"SESSION_REVISION_CONFLICT");Map<String,Object> answers=in.answers()==null?Map.of():in.answers();long next=s.revision()+1;db.update("update sessions set answers=cast(? as jsonb),revision=? where id=?",stringify(answers),next,id);return Map.of("acceptedRevision",next,"answers",answers,"validation",validateAnswers(release(s.releaseId()).pkg(),answers));}
 @PostMapping("/sessions/{id}/validate") Map<String,Object> validate(@PathVariable UUID id,@RequestHeader(value="X-Respondent-Session",required=false) String token){var s=respondent(id,token);return Map.of("errors",validateAnswers(release(s.releaseId()).pkg(),parse(s.answers())),"reviewDigest",UUID.nameUUIDFromBytes(s.answers().getBytes()).toString());}
 @PostMapping("/sessions/{id}/submissions") ResponseEntity<?> submit(@PathVariable UUID id,@RequestHeader(value="X-Respondent-Session",required=false) String token,@RequestBody Submit in){var s=respondent(id,token);if(!Objects.equals(in.sessionRevision(),s.revision()))throw new ResponseStatusException(HttpStatus.CONFLICT,"REVIEW_STALE");var errors=validateAnswers(release(s.releaseId()).pkg(),parse(s.answers()));if(!errors.isEmpty())return ResponseEntity.unprocessableEntity().body(Map.of("code","VALIDATION_FAILED","errors",errors));UUID sub=UUID.randomUUID();Map<String,Object> envelope=Map.of("contractVersion","4.0.0","submissionId",sub,"formId",s.formId(),"answers",parse(s.answers()),"submittedAt",Instant.now().toString());db.update("insert into submissions(id,form_id,session_id,envelope) values(?,?,?,cast(? as jsonb))",sub,s.formId(),id,stringify(envelope));db.update("update sessions set status='SUBMITTED' where id=?",id);audit("SUBMISSION_ACCEPTED",sub);return ResponseEntity.status(201).body(Map.of("receiptId",sub,"submissionId",sub,"message","Your response has been received."));}
 @GetMapping(value="/workspaces/{workspace}/submissions",produces=MediaType.APPLICATION_JSON_VALUE) List<Map<String,Object>> submissions(@PathVariable String workspace,@RequestHeader(value="X-Staff-Session",required=false) String token){UUID ws=authorize(workspace,token);return db.query("select s.id,s.form_id,s.submitted_at from submissions s join forms f on f.id=s.form_id where f.workspace_id=? order by s.submitted_at desc",(rs,n)->Map.of("id",rs.getObject("id").toString(),"formId",rs.getObject("form_id").toString(),"submittedAt",rs.getObject("submitted_at").toString()),ws);}
 @GetMapping("/workspaces/{workspace}/submissions/{id}") Object submission(@PathVariable String workspace,@PathVariable UUID id,@RequestHeader(value="X-Staff-Session",required=false) String token){UUID ws=authorize(workspace,token);try{return parse(db.queryForObject("select s.envelope::text from submissions s join forms f on f.id=s.form_id where s.id=? and f.workspace_id=?",String.class,id,ws));}catch(Exception e){throw missing();}}
 @GetMapping(value="/workspaces/{workspace}/exports.csv",produces="text/csv") String csv(@PathVariable String workspace,@RequestHeader(value="X-Staff-Session",required=false) String token){authorize(workspace,token);StringBuilder b=new StringBuilder("submission_id,form_id,submitted_at,answers\\n");db.query("select id,form_id,submitted_at,envelope->'answers' answers from submissions order by submitted_at desc",(org.springframework.jdbc.core.RowCallbackHandler)rs->b.append(rs.getObject("id")).append(',').append(rs.getObject("form_id")).append(',').append(rs.getObject("submitted_at")).append(",\"").append(rs.getString("answers").replace("\"","\"\"")).append("\"\n"));return b.toString();}
 private record F(UUID id,long revision,String definition){} private record R(UUID id,String pkg){} private record S(UUID id,UUID formId,UUID releaseId,long revision,String answers,String status){}
 private R release(UUID id){return db.queryForObject("select id,package::text from form_releases where id=?",(rs,n)->new R((UUID)rs.getObject(1),rs.getString(2)),id);} private S respondent(UUID id,String token){try{if(token==null)throw new Exception();return db.queryForObject("select id,form_id,release_id,revision,answers::text,status from sessions where id=? and respondent_token=? and expires_at>now()",(rs,n)->new S((UUID)rs.getObject(1),(UUID)rs.getObject(2),(UUID)rs.getObject(3),rs.getLong(4),rs.getString(5),rs.getString(6)),id,UUID.fromString(token));}catch(Exception e){throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Respondent session required");}} private void owned(String workspace,String token,UUID form){UUID ws=authorize(workspace,token);if(db.queryForObject("select count(*) from forms where id=? and workspace_id=?",Integer.class,form,ws)==0)throw missing();} private R latestRelease(UUID form){try{return db.queryForObject("select id,package::text from form_releases where form_id=? order by version desc limit 1",(rs,n)->new R((UUID)rs.getObject(1),rs.getString(2)),form);}catch(Exception e){throw new ResponseStatusException(HttpStatus.NOT_FOUND,"No published release");}} private UUID authorize(String workspace,String token){try{UUID a=db.queryForObject("select account_id from staff_sessions where token=? and expires_at>now()",UUID.class,UUID.fromString(token));UUID w=db.queryForObject("select id from workspaces where workspace_key=?",UUID.class,workspace);if(db.queryForObject("select count(*) from memberships where account_id=? and workspace_id=?",Integer.class,a,w)==0)throw new Exception();return w;}catch(Exception e){throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Valid staff workspace session required");}}
 private F formRow(UUID id){try{return db.queryForObject("select id,revision,definition::text from forms where id=?",(rs,n)->new F((UUID)rs.getObject(1),rs.getLong(2),rs.getString(3)),id);}catch(Exception e){throw missing();}}
 private S sessionRow(UUID id){try{return db.queryForObject("select id,form_id,release_id,revision,answers::text,status from sessions where id=?",(rs,n)->new S((UUID)rs.getObject(1),(UUID)rs.getObject(2),(UUID)rs.getObject(3),rs.getLong(4),rs.getString(5),rs.getString(6)),id);}catch(Exception e){throw missing();}}
 private Map<String,Object> sessionView(S s){return Map.of("sessionId",s.id(),"revision",s.revision(),"answers",parse(s.answers()),"status",s.status(),"definition",parse(release(s.releaseId()).pkg()));}
 @SuppressWarnings("unchecked") private Map<String,Object> parse(String s){try{return json.readValue(s,Map.class);}catch(Exception e){throw new IllegalArgumentException(e);}} private String stringify(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalArgumentException(e);}}
 private Map<String,Object> sampleDefinition(String key,String title){
   Map<String,Object> name=Map.of("id","full-name","type","text","label","Your full name","required",true);
   Map<String,Object> contact=Map.of("id","contact-method","type","choice","label","Preferred contact method","required",true,"options",List.of(Map.of("id","email","label","Email"),Map.of("id","phone","label","Phone")));
   Map<String,Object> email=Map.of("id","email-address","type","text","label","Email address","required",true,"visibleWhen",Map.of("fieldId","contact-method","equals","email"));
   return Map.of("contractVersion","4.0.0","formKey",key,"title",title,"pages",List.of(Map.of("id","page-intake","title","Tell us about yourself","fields",List.of(name,contact,email))));
 }
 private void validateDefinition(Map<String,Object> d){if(!"4.0.0".equals(d.get("contractVersion"))||!d.containsKey("pages"))throw bad("DEFINITION_INVALID","Definition must use contract 4.0.0 and include pages.");}
 @SuppressWarnings("unchecked") private List<Map<String,Object>> validateAnswers(String definition,Map<String,Object> answers){List<Map<String,Object>> errors=new ArrayList<>();Object pages=parse(definition).get("pages");if(pages instanceof List<?> list)for(Object p:list){Object fields=((Map<String,Object>)p).get("fields");if(fields instanceof List<?> fs)for(Object x:fs){Map<String,Object> f=(Map<String,Object>)x;boolean visible=true;if(f.get("visibleWhen") instanceof Map<?,?> r){Map<String,Object> rule=(Map<String,Object>)r;visible=Objects.equals(answers.get(rule.get("fieldId")),rule.get("equals"));}if(visible&&Boolean.TRUE.equals(f.get("required"))&&(answers.get(f.get("id"))==null||answers.get(f.get("id")).toString().trim().isEmpty()))errors.add(Map.of("fieldId",f.get("id"),"message","This field is required."));}}return errors;}
 private void audit(String a,UUID id){db.update("insert into audit_events(id,action,resource_id) values(?,?,?)",UUID.randomUUID(),a,id);}private String etag(long rev){return "\""+rev+"\"";}private ResponseStatusException bad(String c,String d){return new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,c+": "+d);}private ResponseStatusException missing(){return new ResponseStatusException(HttpStatus.NOT_FOUND,"Resource not found");}
}
