package com.kodeboxx.smartintake;

import java.time.*;import java.util.*;import org.springframework.http.*;import org.springframework.jdbc.core.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import com.fasterxml.jackson.databind.*;
import org.springframework.boot.*;import org.springframework.boot.autoconfigure.*;import org.springframework.context.annotation.*;import org.springframework.web.servlet.config.annotation.*;

@SpringBootApplication public class SmartIntakeApplication {
 public static void main(String[] args){SpringApplication.run(SmartIntakeApplication.class,args);}
 @Bean WebMvcConfigurer cors(){return new WebMvcConfigurer(){public void addCorsMappings(CorsRegistry r){r.addMapping("/v1/**").allowedOrigins("http://localhost:4200").allowedMethods("GET","POST","PUT","PATCH","DELETE");}};}
}
@RestController @RequestMapping("/v1") class Api {
 private final JdbcTemplate db; private final ObjectMapper json;
 Api(JdbcTemplate db,ObjectMapper json){this.db=db;this.json=json;}
 record CreateForm(String formKey,String title){} record Draft(Map<String,Object> definition){} record StartSession(String locale,String timeZone){} record PatchSession(Long baseRevision,Map<String,Object> answers){} record Submit(Long sessionRevision){}
 @GetMapping("/health") Map<String,Object> health(){return Map.of("status","UP","service","smart-intake-api","contractVersion","4.0.0");}
 @GetMapping("/capabilities") Map<String,Object> capabilities(){return Map.of("contractVersion","4.0.0","fieldTypes",List.of("text","integer","decimal","boolean","choice","multiChoice","date","object","list","attachments","drawing"),"operators",List.of("equals","notEquals","isAnswered","greaterThan","contains"));}
 @GetMapping("/workspaces/{workspace}/forms") List<Map<String,Object>> forms(@PathVariable String workspace){return db.query("select id,form_key,title,status,revision,updated_at from forms order by updated_at desc",(rs,n)->Map.of("id",rs.getObject("id").toString(),"formKey",rs.getString("form_key"),"title",rs.getString("title"),"status",rs.getString("status"),"revision",rs.getLong("revision"),"updatedAt",rs.getObject("updated_at").toString()));}
 @PostMapping("/workspaces/{workspace}/forms") ResponseEntity<?> create(@PathVariable String workspace,@RequestBody CreateForm in){if(in.formKey()==null||!in.formKey().matches("[a-z][a-z0-9-]{2,99}"))throw bad("FORM_KEY_INVALID","Use a lowercase stable key of at least three characters."); UUID id=UUID.randomUUID();Map<String,Object> def=sampleDefinition(in.formKey(),in.title());db.update("insert into forms(id,form_key,title,definition) values(?,?,?,cast(? as jsonb))",id,in.formKey(),in.title(),stringify(def));audit("FORM_CREATED",id);return ResponseEntity.status(201).eTag(etag(1)).body(Map.of("id",id,"draftId",id,"revision",1,"definition",def));}
 @GetMapping("/workspaces/{workspace}/forms/{form}/drafts/{draft}") ResponseEntity<?> draft(@PathVariable UUID form){var row=formRow(form);return ResponseEntity.ok().eTag(etag(row.revision())).body(Map.of("id",form,"revision",row.revision(),"definition",parse(row.definition()),"diagnostics",List.of()));}
 @PutMapping("/workspaces/{workspace}/forms/{form}/drafts/{draft}") ResponseEntity<?> save(@PathVariable UUID form,@RequestHeader(value="If-Match",required=false) String match,@RequestBody Draft in){var row=formRow(form);if(match==null)throw new ResponseStatusException(HttpStatus.PRECONDITION_REQUIRED,"If-Match required");if(!match.equals(etag(row.revision())))throw new ResponseStatusException(HttpStatus.PRECONDITION_FAILED,"Draft changed; reload to resolve conflict"); validateDefinition(in.definition());long next=row.revision()+1;db.update("update forms set definition=cast(? as jsonb), revision=?, updated_at=now() where id=?",stringify(in.definition()),next,form);audit("DRAFT_SAVED",form);return ResponseEntity.ok().eTag(etag(next)).body(Map.of("revision",next,"definition",in.definition(),"diagnostics",List.of()));}
 @PostMapping("/workspaces/{workspace}/forms/{form}/releases") ResponseEntity<?> publish(@PathVariable UUID form){var row=formRow(form);validateDefinition(parse(row.definition()));int version=db.queryForObject("select coalesce(max(version),0)+1 from form_releases where form_id=?",Integer.class,form);UUID release=UUID.randomUUID();db.update("insert into form_releases(id,form_id,version,package) values(?,?,?,cast(? as jsonb))",release,form,version,row.definition());db.update("update forms set status='PUBLISHED',updated_at=now() where id=?",form);audit("FORM_PUBLISHED",form);return ResponseEntity.status(201).body(Map.of("releaseId",release,"version",version,"shareId",form.toString(),"status","PUBLISHED"));}
 @PostMapping("/public/forms/{share}/sessions") ResponseEntity<?> start(@PathVariable UUID share,@RequestBody(required=false) StartSession in){formRow(share);UUID id=UUID.randomUUID();String locale=in==null||in.locale()==null?"en":in.locale();db.update("insert into sessions(id,form_id,locale,answers) values(?,?,?,cast('{}' as jsonb))",id,share,locale);return ResponseEntity.status(201).body(Map.of("sessionId",id,"revision",0,"locale",locale,"release",parse(formRow(share).definition()),"expiresAt",Instant.now().plus(Duration.ofDays(7)).toString()));}
 @GetMapping("/sessions/{id}") Map<String,Object> session(@PathVariable UUID id){return sessionView(id);}
 @PatchMapping("/sessions/{id}") Map<String,Object> patch(@PathVariable UUID id,@RequestBody PatchSession in){var s=sessionRow(id);if(!s.status().equals("DRAFT"))throw bad("SESSION_CLOSED","This response has already been submitted.");if(!Objects.equals(in.baseRevision(),s.revision()))throw new ResponseStatusException(HttpStatus.CONFLICT,"SESSION_REVISION_CONFLICT");Map<String,Object> answers=in.answers()==null?Map.of():in.answers();long next=s.revision()+1;db.update("update sessions set answers=cast(? as jsonb),revision=? where id=?",stringify(answers),next,id);return Map.of("acceptedRevision",next,"answers",answers,"validation",validateAnswers(formRow(s.formId()).definition(),answers));}
 @PostMapping("/sessions/{id}/validate") Map<String,Object> validate(@PathVariable UUID id){var s=sessionRow(id);return Map.of("errors",validateAnswers(formRow(s.formId()).definition(),parse(s.answers())),"reviewDigest",UUID.nameUUIDFromBytes(s.answers().getBytes()).toString());}
 @PostMapping("/sessions/{id}/submissions") ResponseEntity<?> submit(@PathVariable UUID id,@RequestBody Submit in){var s=sessionRow(id);if(!Objects.equals(in.sessionRevision(),s.revision()))throw new ResponseStatusException(HttpStatus.CONFLICT,"REVIEW_STALE");var errors=validateAnswers(formRow(s.formId()).definition(),parse(s.answers()));if(!errors.isEmpty())return ResponseEntity.unprocessableEntity().body(Map.of("code","VALIDATION_FAILED","errors",errors));UUID sub=UUID.randomUUID();Map<String,Object> envelope=Map.of("contractVersion","4.0.0","submissionId",sub,"formId",s.formId(),"answers",parse(s.answers()),"submittedAt",Instant.now().toString());db.update("insert into submissions(id,form_id,session_id,envelope) values(?,?,?,cast(? as jsonb))",sub,s.formId(),id,stringify(envelope));db.update("update sessions set status='SUBMITTED' where id=?",id);audit("SUBMISSION_ACCEPTED",sub);return ResponseEntity.status(201).body(Map.of("receiptId",sub,"submissionId",sub,"message","Your response has been received."));}
 @GetMapping(value="/workspaces/{workspace}/submissions",produces=MediaType.APPLICATION_JSON_VALUE) List<Map<String,Object>> submissions(@PathVariable String workspace){return db.query("select id,form_id,submitted_at from submissions order by submitted_at desc",(rs,n)->Map.of("id",rs.getObject("id").toString(),"formId",rs.getObject("form_id").toString(),"submittedAt",rs.getObject("submitted_at").toString()));}
 @GetMapping("/workspaces/{workspace}/submissions/{id}") Object submission(@PathVariable UUID id){return parse(db.queryForObject("select envelope::text from submissions where id=?",String.class,id));}
 @GetMapping(value="/workspaces/{workspace}/exports.csv",produces="text/csv") String csv(@PathVariable String workspace){StringBuilder b=new StringBuilder("submission_id,form_id,submitted_at,answers\\n");db.query("select id,form_id,submitted_at,envelope->'answers' answers from submissions order by submitted_at desc",(org.springframework.jdbc.core.RowCallbackHandler)rs->b.append(rs.getObject("id")).append(',').append(rs.getObject("form_id")).append(',').append(rs.getObject("submitted_at")).append(",\"").append(rs.getString("answers").replace("\"","\"\"")).append("\"\n"));return b.toString();}
 private record F(UUID id,long revision,String definition){} private record S(UUID id,UUID formId,long revision,String answers,String status){}
 private F formRow(UUID id){try{return db.queryForObject("select id,revision,definition::text from forms where id=?",(rs,n)->new F((UUID)rs.getObject(1),rs.getLong(2),rs.getString(3)),id);}catch(Exception e){throw missing();}}
 private S sessionRow(UUID id){try{return db.queryForObject("select id,form_id,revision,answers::text,status from sessions where id=?",(rs,n)->new S((UUID)rs.getObject(1),(UUID)rs.getObject(2),rs.getLong(3),rs.getString(4),rs.getString(5)),id);}catch(Exception e){throw missing();}}
 private Map<String,Object> sessionView(UUID id){var s=sessionRow(id);return Map.of("sessionId",s.id(),"revision",s.revision(),"answers",parse(s.answers()),"status",s.status(),"definition",parse(formRow(s.formId()).definition()));}
 @SuppressWarnings("unchecked") private Map<String,Object> parse(String s){try{return json.readValue(s,Map.class);}catch(Exception e){throw new IllegalArgumentException(e);}} private String stringify(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalArgumentException(e);}}
 private Map<String,Object> sampleDefinition(String key,String title){
   Map<String,Object> name=Map.of("id","full-name","type","text","label","Your full name","required",true);
   Map<String,Object> contact=Map.of("id","contact-method","type","choice","label","Preferred contact method","required",true,"options",List.of(Map.of("id","email","label","Email"),Map.of("id","phone","label","Phone")));
   Map<String,Object> email=Map.of("id","email-address","type","text","label","Email address","required",true,"visibleWhen",Map.of("fieldId","contact-method","equals","email"));
   return Map.of("contractVersion","4.0.0","formKey",key,"title",title,"pages",List.of(Map.of("id","page-intake","title","Tell us about yourself","fields",List.of(name,contact,email))));
 }
 private void validateDefinition(Map<String,Object> d){if(!"4.0.0".equals(d.get("contractVersion"))||!d.containsKey("pages"))throw bad("DEFINITION_INVALID","Definition must use contract 4.0.0 and include pages.");}
 @SuppressWarnings("unchecked") private List<Map<String,Object>> validateAnswers(String definition,Map<String,Object> answers){List<Map<String,Object>> errors=new ArrayList<>();Object pages=parse(definition).get("pages");if(pages instanceof List<?> list)for(Object p:list){Object fields=((Map<String,Object>)p).get("fields");if(fields instanceof List<?> fs)for(Object x:fs){Map<String,Object> f=(Map<String,Object>)x;boolean visible=true;if(f.get("visibleWhen") instanceof Map<?,?> r){Map<String,Object> rule=(Map<String,Object>)r;visible=Objects.equals(answers.get(rule.get("fieldId")),rule.get("equals"));}if(visible&&Boolean.TRUE.equals(f.get("required"))&&(answers.get(f.get("id"))==null||answers.get(f.get("id")).toString().trim().isEmpty()))errors.add(Map.of("fieldId",f.get("id"),"message","This field is required."));}}return errors;}
 private void audit(String a,UUID id){db.update("insert into audit_events(id,action,resource_id) values(?,?,?)",UUID.randomUUID(),a,id);}private String etag(long rev){return "\""+rev+"\"";}private ResponseStatusException bad(String c,String d){return new ResponseStatusException(HttpStatus.UNPROCESSABLE_ENTITY,c+": "+d);}private ResponseStatusException missing(){return new ResponseStatusException(HttpStatus.NOT_FOUND,"Resource not found");}
}
