import { Component, computed, inject, signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { CuiAlertComponent, CuiButtonComponent, CuiCardComponent, CuiEmptyStateComponent, CuiInputComponent, CuiSelectComponent, CuiTagComponent } from '@certinal/ui';
import { StaffSessionStore } from '../../core/m5-session.store';
import { WORKSPACE_ROLES, hasWorkspaceRole } from '../../core/workspace-roles';
import { SmartIntakeApiService } from '../../smart-intake-api.service';

type ViewState = 'loading' | 'ready' | 'empty' | 'invalid' | 'denied' | 'expired' | 'no-email' | 'error';

@Component({ selector: 'app-administration-page', standalone: true, imports: [CuiAlertComponent, CuiButtonComponent, CuiCardComponent, CuiEmptyStateComponent, CuiInputComponent, CuiSelectComponent, CuiTagComponent], template: `
<section class="mx-auto max-w-6xl space-y-5" data-testid="administration-page" [attr.data-state]="state()"><div><p class="type-caption">ADMINISTRATION</p><h1 class="type-h3">{{ title() }}</h1><p class="type-caption">{{ session.currentOrganization()?.name || 'No selected organization' }} · {{ session.currentWorkspace()?.name || 'No selected workspace' }}</p></div>
@if (message()) { <cui-alert [variant]="state() === 'denied' || state() === 'invalid' ? 'error' : 'warning'" [title]="state()">{{ message() }}</cui-alert> }
@if (state() === 'loading') { <cui-card><p class="type-body">Loading server-authorized administration context…</p></cui-card> }
@else if (state() === 'empty') { <cui-empty-state icon="inbox" title="Nothing here yet" description="No organization records are available in this context." /> }
@else if (state() !== 'denied' && state() !== 'expired') {
  @if (screen === 'platform-organizations') { <cui-card><div class="flex flex-wrap items-end gap-3"><cui-input label="Organization name" [(value)]="organizationName" /><cui-button [disabled]="!isPlatformAdmin()" (buttonClick)="createOrganization()">Create organization</cui-button></div>@for (organization of organizations(); track organization.id) { <div class="mt-4 flex items-center justify-between"><span class="type-body">{{ organization.name }}</span><cui-tag tone="emerald">{{ organization.status }}</cui-tag></div> }</cui-card> }
  @else if (screen === 'organization-settings') { <cui-card><cui-input label="Organization name" [(value)]="organizationName" /><cui-button class="mt-3" [disabled]="!canManage()" (buttonClick)="saveOrganization()">Save organization</cui-button></cui-card> }
  @else if (screen === 'user-list' || screen === 'user-detail' || screen === 'add-user' || screen === 'role-assignment') { <cui-card><div class="flex flex-wrap items-end gap-3"><cui-input label="User email" type="email" [(value)]="email" [error]="state() === 'invalid' ? 'Enter a valid email address.' : undefined" /><cui-select label="Organization role" [options]="roleOptions" [(value)]="role" /><cui-select label="Workspace role" [options]="workspaceRoleOptions" [(value)]="workspaceRole" /><cui-button [disabled]="!canManage()" (buttonClick)="addUser()">Add user</cui-button></div>@for (user of users(); track user.id) { <div class="mt-4 flex flex-wrap items-center justify-between gap-2"><div><p class="type-body">{{ user.email }}</p><p class="type-caption">{{ user.roles.join(', ') || 'member' }}</p></div>@if (canManage()) { <div class="flex gap-2"><cui-button size="sm" variant="secondary" (buttonClick)="assignRoles(user.id, user.revision)">Assign workspace role</cui-button><cui-button size="sm" variant="tertiary" (buttonClick)="invite(user.id)">Invite</cui-button></div> }</div> }</cui-card> }
  @else if (screen === 'invitation-delivery') { <cui-card><p class="type-body">Invitation delivery</p><p class="type-caption">When email is unavailable, provide the copy-link path only after the server creates an invitation.</p>@if (copyLink()) { <cui-alert class="mt-3" variant="warning" title="No-email delivery">Copy this safe invitation instruction: {{ copyLink() }}</cui-alert> }</cui-card> }
  @else { <cui-card><p class="type-body">Provider and policy controls</p><p class="type-caption">Policies shown here are loaded for the selected server-authorized organization.</p><p class="type-caption mt-3">{{ policies().length }} policy record(s) available.</p></cui-card> }
}
</section>` })
export class AdministrationPageComponent {
  readonly route = inject(ActivatedRoute); readonly api = inject(SmartIntakeApiService); readonly session = inject(StaffSessionStore);
  readonly screen = this.route.snapshot.data['screen'] as string; readonly state = signal<ViewState>('loading'); readonly message = signal(''); readonly organizations = signal<any[]>([]); readonly users = signal<any[]>([]); readonly policies = signal<unknown[]>([]); readonly copyLink = signal('');
  organizationName = ''; email = ''; role = 'member'; workspaceRole = 'author'; readonly roleOptions = [{ label: 'Member', value: 'member' }, { label: 'Administrator', value: 'administrator' }]; readonly workspaceRoleOptions = WORKSPACE_ROLES.map((role) => ({ label: role, value: role }));
  readonly title = computed(() => ({ 'platform-organizations': 'Platform organizations', 'organization-settings': 'Organization settings', 'user-list': 'Users', 'add-user': 'Add user', 'user-detail': 'User details', 'role-assignment': 'Role assignment', 'invitation-delivery': 'Invitations', 'provider-policy': 'Provider policy' }[this.screen] ?? 'Administration'));
  constructor() { this.load(); }
  canManage(): boolean { return hasWorkspaceRole(this.session.currentRoles(), 'workspace-administrator'); }
  isPlatformAdmin(): boolean { return this.canManage(); }
  load(): void { const organizationId = this.session.currentOrganizationId(); if (!organizationId && this.screen !== 'platform-organizations') { this.state.set('empty'); return; } this.state.set('loading'); const request = this.screen === 'platform-organizations' ? this.api.platformOrganizations() : this.screen === 'provider-policy' ? this.api.organizationPolicies(organizationId!) : this.api.organizationUsers(organizationId!); request.subscribe({ next: (result: any) => { if (this.screen === 'platform-organizations') this.organizations.set(result); else if (this.screen === 'provider-policy') this.policies.set(result); else this.users.set(result); this.organizationName = this.session.currentOrganization()?.name ?? ''; this.state.set(result.length ? 'ready' : 'empty'); }, error: (error) => this.fail(error.status) }); }
  createOrganization(): void { if (!this.organizationName.trim()) { this.state.set('invalid'); return; } this.api.createPlatformOrganization({ name: this.organizationName }).subscribe({ next: () => this.load(), error: (error) => this.fail(error.status) }); }
  saveOrganization(): void { const organization = this.session.currentOrganization(); if (!organization || !this.organizationName.trim()) { this.state.set('invalid'); return; } this.api.updateOrganization(organization.organizationId, 0, { name: this.organizationName }).subscribe({ next: () => this.message.set('Organization settings saved.'), error: (error) => this.fail(error.status) }); }
  addUser(): void { const organizationId = this.session.currentOrganizationId(); if (!organizationId || !/^\S+@\S+\.\S+$/.test(this.email)) { this.state.set('invalid'); return; } this.api.addOrganizationUser(organizationId, { email: this.email, roles: [this.role as 'member' | 'administrator'] }).subscribe({ next: () => { this.email = ''; this.load(); }, error: (error) => this.fail(error.status) }); }
  assignRoles(userId: string, revision: number): void { const workspace = this.session.currentWorkspaceId(); if (!workspace || !this.canManage()) return; this.api.assignWorkspaceRoles(workspace, userId, revision, { roles: [this.workspaceRole] as any }).subscribe({ next: () => this.message.set('Workspace role assignment saved.'), error: (error) => this.fail(error.status) }); }
  invite(userId: string): void { const organization = this.session.currentOrganizationId(); if (!organization) return; this.api.inviteOrganizationUser(organization, userId).subscribe({ next: (invitation) => { this.copyLink.set(`Invitation ${invitation.id} is ready for administrator-assisted delivery.`); this.state.set('no-email'); }, error: (error) => this.fail(error.status) }); }
  private fail(status: number): void { const state: ViewState = status === 403 ? 'denied' : status === 401 || status === 419 ? 'expired' : status === 503 ? 'no-email' : 'error'; this.state.set(state); this.message.set(state === 'no-email' ? 'Email delivery is unavailable. Use the copy-link path.' : 'The server could not complete this administration request.'); }
}
