#!/usr/bin/env node
/** Generate consumer utilities from the immutable Certinal theme for Angular's CSS pipeline. */
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from '../../frontend/node_modules/tailwindcss/dist/lib.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const frontend = join(root, 'frontend');
const sourceRoots = [join(frontend, 'src'), join(frontend, 'projects/certinal-ui/src')];
const output = join(frontend, 'src/generated-certinal-utilities.css');
const tokens = (await readFile(join(frontend, 'projects/certinal-ui/src/styles/tokens.css'), 'utf8'))
  .split('\n').filter((line) => !line.startsWith('@import ') && !line.startsWith('@source ')).join('\n');

async function files(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  return (await Promise.all(entries.map((entry) => entry.isDirectory() ? files(join(directory, entry.name)) : [join(directory, entry.name)]))).flat();
}

const candidates = new Set();
for (const file of (await Promise.all(sourceRoots.map(files))).flat()) {
  if (!/\.(?:ts|html)$/.test(file) || file === output) continue;
  const text = await readFile(file, 'utf8');
  for (const match of text.matchAll(/\bclass\s*=\s*["']([^"']+)["']/g)) {
    for (const candidate of match[1].split(/\s+/)) candidates.add(candidate);
  }
  for (const match of text.matchAll(/\bclass:\s*['"]([^'"]+)['"]/g)) {
    for (const candidate of match[1].split(/\s+/)) candidates.add(candidate);
  }
  // Certinal's class maps deliberately live in TypeScript rather than templates.
  // Include quoted utility lists from those maps without modifying snapshot files.
  for (const match of text.matchAll(/['"]([^'"\n]*(?:-|:)[^'"\n]*)['"]/g)) {
    for (const candidate of match[1].split(/\s+/)) candidates.add(candidate);
  }
}

const compiler = await compile(`@import "tailwindcss/theme.css";\n${tokens}\n@tailwind utilities;`, {
  base: frontend,
  loadStylesheet: async (id, base) => {
    const packagePath = id.startsWith('tailwindcss/')
      ? join(frontend, 'node_modules', id.replace('tailwindcss/', 'tailwindcss/'))
      : resolve(base, id);
    return { content: await readFile(packagePath, 'utf8'), base: dirname(packagePath) };
  },
});
const banner = `/* Generated by tools/frontend/build_tailwind_utilities.mjs from ${relative(frontend, join(frontend, 'projects/certinal-ui/src/styles/tokens.css'))}. Do not hand-edit. */\n`;
await writeFile(output, banner + compiler.build([...candidates].sort()));
console.log(`generated Certinal consumer utilities: ${candidates.size} candidates`);
