#!/usr/bin/env python3
"""Deterministically generate checked-in M2 registry, Java/TypeScript models and resources.

Generator metadata is deliberately pinned in ``generation``.  It never emits a
clock, a local path, or environment-dependent bytes.  The generated registry is
the runtime/publication source; this program only refreshes it from the seven
normative schema documents and frozen M0 operation inventory.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile

import yaml
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
CONTRACT = ROOT / "docs/contracts/smart-form-builder-lite/4.0.0"
INDEX = CONTRACT / "index.json"
OPENAPI = ROOT / "docs/api/openapi.yaml"
OPERATIONS = ROOT / "docs/acceptance/v1.1/denominators/o-total.json"
REGISTRY = CONTRACT / "capabilities.registry.json"
JAVA_MODELS = ROOT / "backend/src/generated/java/com/kodeboxx/smartintake/generated/contract"
JAVA_OPENAPI = ROOT / "tools/contracts/openapi-java-models.yaml"
TS = ROOT / "frontend/src/app/generated/contracts.ts"
API_TS = ROOT / "frontend/src/app/generated/api.ts"
FIXTURES_TS = ROOT / "frontend/src/app/generated/contract-fixtures.ts"
SCHEMAS_TS = ROOT / "frontend/src/app/generated/contract-schemas.ts"
RESOURCES = ROOT / "backend/src/main/resources/contracts/smart-form-builder-lite/4.0.0"
OPENAPI_RESOURCE = ROOT / "backend/src/main/resources/contracts/openapi-4.0.0.yaml"
FRONTEND_ASSETS = ROOT / "frontend/src/assets/contracts/smart-form-builder-lite/4.0.0"

GENERATION = {
    "generator": "tools/contracts/generate_contract_artifacts.py",
    "generatorVersion": "1.2.0",
    "python": "3.12",
    "schemaDialect": "https://json-schema.org/draft/2020-12/schema",
    "openapi": "3.1.0",
    "modelStrategy": "strongly-typed-schema-domain-records-with-extension-fields",
    "javaOpenApiGenerator": "7.10.0 (pinned; generated by openapi-generator-maven-plugin from a deterministic local OpenAPI bundle)",
    "openapiTypeScript": "7.6.1",
    "timestampPolicy": "none",
    "absolutePathPolicy": "forbidden",
}
LIMITS = [
    ("definitionJsonBytes", 5 * 1024 * 1024, "bytes"),
    ("typedDraftOrSubmissionJsonBytes", 1024 * 1024, "bytes"),
    ("fileBytes", 25 * 1024 * 1024, "bytes"),
    ("filesPerQuestion", 10, "count"),
    ("attachmentBytesPerSession", 100 * 1024 * 1024, "bytes"),
    ("itemsPerRepeater", 500, "count"),
    ("nestedRepeaterLevels", 3, "count"),
    ("expandedActiveAnswerCells", 10000, "count"),
    ("expressionDepth", 20, "count"),
    ("astNodesPerPackage", 10000, "count"),
    ("evaluationStepsPerMutation", 100000, "count"),
]

def canonical(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n").encode()

def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()

def load(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))

JAVA_MODEL_NAMES = {
    "package": "PackageDocument",
    "expression": "ExpressionDocument",
    "input-answer": "InputAnswerDocument",
    "typed-answer": "TypedAnswerDocument",
    "runtime-manifest": "RuntimeManifestDocument",
    "submission-envelope": "SubmissionEnvelopeDocument",
    "event": "EventDocument",
}


def java_component_name(model: str, definition: str) -> str:
    return model + "".join(part[:1].upper() + part[1:] for part in definition.replace("-", "_").split("_"))


def java_model_projection(source: dict[str, Any]) -> dict[str, Any]:
    """Make Draft 2020-12 union roots consumable by Java Generator's OAS 3.1 reader.

    Generator 7.10.0 otherwise selects only the first branch of a root ``oneOf``.
    The projection is build-only: it derives the union's fields/enums from the
    authoritative schema and keeps scalar answer values as ``Object`` so
    canonical string values survive Jackson round trips exactly.
    """
    variants = source.get("oneOf")
    if not isinstance(variants, list):
        return source
    definitions = source.get("$defs", {})
    resolved = [definitions[ref["$ref"].removeprefix("#/$defs/")] for ref in variants if ref.get("$ref", "").startswith("#/$defs/")]
    if len(resolved) != len(variants):
        return source
    properties: dict[str, Any] = {}
    required = set(resolved[0].get("required", []))
    for variant in resolved:
        required &= set(variant.get("required", []))
        for name, property_schema in variant.get("properties", {}).items():
            if name not in properties:
                properties[name] = property_schema
            elif name in {"status", "type"}:
                values = properties[name].get("enum", []) + property_schema.get("enum", [])
                if "const" in properties[name]: values.append(properties[name]["const"])
                if "const" in property_schema: values.append(property_schema["const"])
                properties[name] = {"enum": list(dict.fromkeys(values))}
    if "value" in properties:
        properties["value"] = {}
    return {
        **{key: value for key, value in source.items() if key not in {"oneOf", "allOf"}},
        "type": "object",
        "additionalProperties": False,
        "required": sorted(required),
        "properties": properties,
    }


def java_openapi_bundle() -> bytes:
    """Bundle local OpenAPI/component/schema references for OpenAPI Generator 7.10.0.

    The public OpenAPI intentionally retains external JSON Schema references for
    publication. The generator cannot dereference their normative HTTPS $id
    values offline, so this deterministic build-only bundle makes all refs local
    without changing the published contract.
    """
    api = yaml.safe_load(OPENAPI.read_text(encoding="utf-8"))
    components = yaml.safe_load((CONTRACT / "openapi-components.yaml").read_text(encoding="utf-8"))["components"]
    schema_sources = {model: java_model_projection(load(CONTRACT / f"{kind}.schema.json")) for kind, model in JAVA_MODEL_NAMES.items()}
    definition_names = {
        (model, definition): java_component_name(model, definition)
        for model, source in schema_sources.items()
        for definition in source.get("$defs", {})
    }

    def transform(value: Any, current_schema: str | None = None) -> Any:
        if isinstance(value, list):
            return [transform(item, current_schema) for item in value]
        if not isinstance(value, dict):
            return value
        transformed = {key: transform(item, current_schema) for key, item in value.items() if key not in {"$id", "$schema"}}
        ref = transformed.get("$ref")
        if not isinstance(ref, str):
            return transformed
        ref = ref.replace("../contracts/smart-form-builder-lite/4.0.0/openapi-components.yaml#/components/", "#/components/")
        for kind, model in JAVA_MODEL_NAMES.items():
            for prefix in (f"./{kind}.schema.json", f"{kind}.schema.json"):
                if ref == prefix:
                    ref = f"#/components/schemas/{model}"
                elif ref.startswith(prefix + "#"):
                    ref = f"#/components/schemas/{model}" + ref[len(prefix):]
        if current_schema and ref == "#":
            ref = f"#/components/schemas/{current_schema}"
        elif current_schema and ref.startswith("#/$defs/"):
            ref = f"#/components/schemas/{definition_names[(current_schema, ref.removeprefix('#/$defs/'))]}"
        transformed["$ref"] = ref
        return transformed

    bundled = transform(api)
    bundled["components"] = transform(components)
    for model, source in schema_sources.items():
        bundled["components"]["schemas"][model] = transform(source, model)
        for definition, definition_schema in source.get("$defs", {}).items():
            bundled["components"]["schemas"][definition_names[(model, definition)]] = transform(definition_schema, model)
    # OpenAPI Generator emits only schemas reachable from an operation. Events
    # are intentionally published as a standalone schema, so retain that
    # reachability in this private generation bundle without changing the
    # public CapabilityRegistry contract.
    bundled["components"]["schemas"]["CapabilityRegistry"]["properties"]["xGeneratedEventModel"] = {
        "$ref": "#/components/schemas/EventDocument"
    }
    return yaml.safe_dump(bundled, sort_keys=False, allow_unicode=True, width=120).encode("utf-8")

def generated_java_models(bundle: bytes) -> dict[Path, bytes]:
    """Run the pinned Maven plugin into a temporary directory and return every model byte."""
    with tempfile.TemporaryDirectory(prefix="smartintake-openapi-java-") as temp:
        root = Path(temp)
        input_spec = root / "openapi-java-models.yaml"
        output = root / "output"
        input_spec.write_bytes(bundle)
        subprocess.run([
            "mvn", "-q", "openapi-generator:generate@generate-checked-in-contract-models",
            f"-Dopenapi.contract.input={input_spec}",
            f"-Dopenapi.contract.output={output}",
        ], check=True, cwd=ROOT / "backend", capture_output=True, text=True)
        generated_root = output / "com/kodeboxx/smartintake/generated/contract"
        return {JAVA_MODELS / path.relative_to(generated_root): path.read_bytes() for path in sorted(generated_root.rglob("*.java"))}

def generated_ts(kinds: list[str]) -> str:
    return '''// GENERATED by tools/contracts/generate_contract_artifacts.py v1.1.0; DO NOT EDIT.
// Source: seven Smart Form Builder Lite 4.0.0 JSON Schemas. No timestamps or absolute paths.
export const SMART_FORM_CONTRACT_VERSION = '4.0.0' as const;
export type CanonicalInt64 = string & { readonly __canonicalInt64: unique symbol };
export type CanonicalDecimal = string & { readonly __canonicalDecimal: unique symbol };
export type AnswerStatus = 'unanswered' | 'answered' | 'inapplicable' | 'hidden' | 'invalid' | 'calculated';
export type TypedValueType = 'string' | 'integer' | 'decimal' | 'boolean' | 'date' | 'time' | 'dateTime' | 'list' | 'object' | 'attachment';
export interface ContractBase { schemaVersion?: string; contractVersion?: string; engineContract?: string; extensions?: Record<string, unknown>; }
export interface Translation { title?: string; description?: string; labels?: Record<string, string>; }
export interface PackageDocument extends ContractBase { kind: 'package'; formKey: string; definitionVersion: string; titleKey: string; defaultLocale: string; supportedLocales: string[]; translations: Record<string, Translation>; data: unknown; flow: unknown; expressions: Record<string, ExpressionDocument>; }
export interface ExpressionDocument { operator?: string; args?: ExpressionDocument[]; literal?: string | number | boolean | null; fieldId?: string; }
export interface AnswerItem { itemId: string; parentItemId?: string; fields: Record<string, InputAnswerDocument>; }
export interface InputValue { value?: string; items?: AnswerItem[]; attachmentIds?: string[]; }
export interface InputAnswerDocument extends ContractBase { status: AnswerStatus; value?: InputValue; }
export interface Provenance { source: string; changedAt: string; actorId?: string; }
export interface TypedAnswerDocument extends ContractBase { status: AnswerStatus; type?: TypedValueType; value?: CanonicalInt64 | CanonicalDecimal | string | boolean | { items: Array<{ itemId: string; fields: Record<string, TypedAnswerDocument> }> }; provenance?: Provenance; }
export interface RuntimeManifestDocument extends ContractBase { runtimeManifestVersion: string; runtimeManifestHash: string; packageHash: string; policyVersion: string; timeZoneDatabaseVersion: string; }
export interface SubmissionEnvelopeDocument extends ContractBase { submissionId: string; tenantId: string; workspaceId: string; formId: string; sessionId: string; sessionRevision: CanonicalInt64; submittedAt: string; status: string; locale: string; answers: Record<string, TypedAnswerDocument>; }
export interface EventDocument extends ContractBase { eventId: string; type: string; occurredAt: string; tenantId: string; workspaceId: string; formSequence: CanonicalInt64; dataMode: string; }
'''

def generated_fixtures(kinds: list[str]) -> str:
    positive = {kind: load(CONTRACT / "fixtures" / f"{kind}.positive.json") for kind in kinds}
    negative = {kind: load(CONTRACT / "fixtures" / f"{kind}.negative.json") for kind in kinds}
    return "// GENERATED fixture data for AJV contract tests; DO NOT EDIT.\n" + "export const positiveFixtures = " + json.dumps(positive, sort_keys=True, separators=(",", ":")) + " as const;\n" + "export const negativeFixtures = " + json.dumps(negative, sort_keys=True, separators=(",", ":")) + " as const;\n"

def generated_schemas(kinds: list[str]) -> str:
    schemas = {kind: load(CONTRACT / f"{kind}.schema.json") for kind in kinds}
    return "// GENERATED schema test data; DO NOT EDIT.\nexport const contractSchemas = " + json.dumps(schemas, sort_keys=True, separators=(",", ":")) + " as const;\n"

def registry() -> dict[str, Any]:
    index = load(INDEX)
    schemas = []
    schemas_by_kind: dict[str, dict[str, Any]] = {}
    for item in index["schemas"]:
        schema = load(CONTRACT / item["file"])
        schemas_by_kind[item["kind"]] = schema
        schemas.append({"kind": item["kind"], "version": "4.0.0", "id": item["id"], "file": item["file"], "sha256": digest(CONTRACT / item["file"]), "resource": f"contracts/smart-form-builder-lite/4.0.0/{item['file']}"})
    ops = load(OPERATIONS)["members"]
    operation_status = []
    for op in ops:
        implementation = "planned"
        route = None
        if op["method"] == "GET" and op["path"] in {"/v1/capabilities", "/v1/schemas/{kind}/{version}"}:
            implementation, route = "implemented", op["path"]
        operation_status.append({**{key: op[key] for key in ("id", "method", "path", "title")}, "implementationStatus": implementation, "implementedRoute": route, "behaviorClaim": "published contract only" if implementation == "planned" else "contract publication endpoint"})
    return {
        "registryVersion": "1.0.0", "contractVersion": "4.0.0", "generation": GENERATION,
        "openapi": {"version": "3.1.0", "file": "docs/api/openapi.yaml", "sha256": digest(OPENAPI), "resource": "contracts/openapi-4.0.0.yaml"},
        "schemas": schemas,
        "fieldCatalog": schemas_by_kind["package"]["x-catalogRows"],
        "controlValueCompatibility": schemas_by_kind["package"]["x-controlCompatibility"],
        "operatorSignatures": [{"operator": name, "minArgs": arity[0], "maxArgs": arity[1]} for name, arity in schemas_by_kind["expression"]["x-operatorArity"].items()],
        "limits": [{"id": ident, "value": value, "unit": unit, "enforcementStatus": "planned"} for ident, value, unit in LIMITS],
        "versions": {"contract": "4.0.0", "schemaDialect": GENERATION["schemaDialect"], "openapi": "3.1.0", "java": "17", "typescript": "5.8"},
        "operations": {"count": len(operation_status), "statusPolicy": "Only endpoints marked implemented have runtime behavior claims; planned endpoints are contract-published only.", "items": operation_status},
        "assetSupplement": {"id": "M2-get-v1-workspaces-w-assets-assetid-authorized-asset", "counted": False, "implementationStatus": "planned", "reason": "PRD named an authorized asset API without an M0 method/path; the frozen counted O_total remains 82."},
    }

def expected_files() -> dict[Path, bytes]:
    index = load(INDEX)
    kinds = [item["kind"] for item in index["schemas"]]
    files: dict[Path, bytes] = {
        REGISTRY: canonical(registry()), TS: generated_ts(kinds).encode(), FIXTURES_TS: generated_fixtures(kinds).encode(), SCHEMAS_TS: generated_schemas(kinds).encode(), OPENAPI_RESOURCE: OPENAPI.read_bytes(),
        JAVA_OPENAPI: java_openapi_bundle(),
    }
    files.update(generated_java_models(files[JAVA_OPENAPI]))
    files[RESOURCES / "capabilities.registry.json"] = files[REGISTRY]
    for item in index["schemas"]:
        files[RESOURCES / item["file"]] = (CONTRACT / item["file"]).read_bytes()
        files[FRONTEND_ASSETS / item["file"]] = (CONTRACT / item["file"]).read_bytes()
    # The locally pinned openapi-typescript executable creates the API declaration file in a temp directory.
    with tempfile.TemporaryDirectory(prefix="smartintake-openapi-types-") as temp:
        candidate = Path(temp) / "api.ts"
        executable = ROOT / "frontend/node_modules/.bin/openapi-typescript"
        subprocess.run([str(executable), str(OPENAPI), "-o", str(candidate)], check=True, cwd=ROOT, capture_output=True, text=True)
        files[API_TS] = candidate.read_bytes()
    return files

def apply(files: dict[Path, bytes], check: bool) -> list[str]:
    errors=[]
    with tempfile.TemporaryDirectory(prefix="smartintake-contracts-") as temp:
        root=Path(temp)
        for dest, content in files.items():
            candidate=root / dest.relative_to(ROOT)
            candidate.parent.mkdir(parents=True, exist_ok=True)
            candidate.write_bytes(content)
            if not dest.exists() or dest.read_bytes()!=candidate.read_bytes():
                errors.append(str(dest.relative_to(ROOT)))
                if not check:
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copyfile(candidate, dest)
    generated = {path for path in files if path.is_relative_to(JAVA_MODELS)}
    if JAVA_MODELS.exists():
        stale_models = sorted(path for path in JAVA_MODELS.rglob("*.java") if path not in generated)
        for stale in stale_models:
            errors.append(str(stale.relative_to(ROOT)))
            if not check:
                stale.unlink()
    return errors

def main() -> int:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="regenerate to a temporary directory and reject byte drift")
    args=parser.parse_args()
    stale=apply(expected_files(), args.check)
    if stale and args.check:
        print("Generated contract artifacts are stale:", *stale, sep="\n- ")
        return 1
    print("Generated/verified OpenAPI Generator Java 17 models, TypeScript models and immutable resources.")
    return 0
if __name__ == "__main__":
    raise SystemExit(main())
