#!/usr/bin/env python3
"""Generate the additive M4 API contract without changing immutable 4.0.0 bytes."""
from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
LEGACY_API = ROOT / "docs/api/openapi.yaml"
LEGACY_COMPONENTS = ROOT / "docs/contracts/smart-form-builder-lite/4.0.0/openapi-components.yaml"
API = ROOT / "docs/api/openapi-4.1.0.yaml"
COMPONENTS = ROOT / "docs/api/openapi-components-4.1.0.yaml"
RESOURCE = ROOT / "backend/src/main/resources/contracts/openapi-4.1.0.yaml"
HEADER = "# GENERATED by tools/openapi/generate_m4_api_contract.py. DO NOT EDIT.\n"


def operation(op: str, required: list[str], properties: dict[str, Any]) -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["op", "fieldId", *required],
        "properties": {
            "op": {"const": op},
            "fieldId": {"type": "string", "minLength": 1},
            "rowPath": {"$ref": "#/components/schemas/RuntimeRowPath"},
            **properties,
        },
    }


def generated() -> dict[Path, bytes]:
    api = yaml.safe_load(LEGACY_API.read_text(encoding="utf-8"))
    components = yaml.safe_load(LEGACY_COMPONENTS.read_text(encoding="utf-8"))
    api["info"] = copy.deepcopy(api["info"])
    api["info"]["version"] = "4.1.0"
    api["info"]["description"] = (
        "Additive M4 API contract. Canonical package and answer schemas remain 4.0.0; "
        "this API version adds the recursive typed mutation protocol."
    )

    def rewrite(value: Any) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                if key == "$ref" and isinstance(child, str) and child.startswith(
                    "../contracts/smart-form-builder-lite/4.0.0/openapi-components.yaml"
                ):
                    value[key] = child.replace(
                        "../contracts/smart-form-builder-lite/4.0.0/openapi-components.yaml",
                        "./openapi-components-4.1.0.yaml",
                    )
                elif key == "$ref" and isinstance(child, str) and child.startswith(
                    "./openapi-components-4.1.0.yaml#/components/"
                ):
                    value[key] = child.replace("./openapi-components-4.1.0.yaml#/components/", "#/components/")
                elif key == "$ref" and isinstance(child, str) and child.startswith("./") \
                        and ".schema.json" in child:
                    value[key] = "../contracts/smart-form-builder-lite/4.0.0/" + child.removeprefix("./")
                else:
                    rewrite(child)
        elif isinstance(value, list):
            for child in value:
                rewrite(child)

    rewrite(api)
    components["info"]["title"] = "Smart Form Builder Lite 4.1.0 OpenAPI components"
    components["info"]["version"] = "4.1.0"
    rewrite(components)
    schemas = components["components"]["schemas"]
    schemas["RuntimeRowSegment"] = {
        "type": "object",
        "additionalProperties": False,
        "required": ["listFieldId", "itemId"],
        "properties": {
            "listFieldId": {"type": "string", "minLength": 1},
            "itemId": {"$ref": "#/components/schemas/OpaqueId"},
        },
    }
    schemas["RuntimeRowPath"] = {
        "type": "array",
        "maxItems": 3,
        "items": {"$ref": "#/components/schemas/RuntimeRowSegment"},
    }
    input_document = json.loads((ROOT / "docs/contracts/smart-form-builder-lite/4.0.0/input-answer.schema.json")
                                .read_text(encoding="utf-8"))
    input_definitions = input_document.pop("$defs")
    input_document.pop("$schema", None)
    input_document.pop("$id", None)

    def rewrite_input_refs(value: Any) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                if key == "$ref" and child == "#":
                    value[key] = "#/components/schemas/InputAnswerValue"
                elif key == "$ref" and isinstance(child, str) and child.startswith("#/$defs/"):
                    value[key] = "#/components/schemas/InputAnswer_" + child.removeprefix("#/$defs/")
                else:
                    rewrite_input_refs(child)
        elif isinstance(value, list):
            for child in value:
                rewrite_input_refs(child)

    rewrite_input_refs(input_document)
    schemas["InputAnswerValue"] = input_document
    for name, definition in input_definitions.items():
        rewrite_input_refs(definition)
        schemas["InputAnswer_" + name] = definition
    typed_answer = {"$ref": "#/components/schemas/InputAnswerValue"}
    opaque = {"$ref": "#/components/schemas/OpaqueId"}
    schemas["SessionMutation"] = {
        "oneOf": [
            operation("set", ["value"], {"value": typed_answer}),
            operation("clear", [], {}),
            operation("markInvalid", ["reason"], {"reason": {"const": "UNPARSEABLE_INPUT"}}),
            operation(
                "addItem",
                ["itemId"],
                {
                    "itemId": opaque,
                    "initialFields": {
                        "type": "object",
                        "additionalProperties": typed_answer,
                        "default": {},
                    },
                },
            ),
            operation("removeItem", ["itemId"], {"itemId": opaque}),
            operation(
                "moveItem",
                ["itemId"],
                {
                    "itemId": opaque,
                    "beforeItemId": {"anyOf": [opaque, {"type": "null"}]},
                },
            ),
        ],
        "discriminator": {"propertyName": "op"},
    }
    schemas["SessionMutationRequest"]["properties"]["operations"]["maxItems"] = 1000
    schemas["ReviewDigest"] = {"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"}
    schemas["Acknowledgment"] = {
        "type": "object",
        "additionalProperties": False,
        "required": ["fieldId", "rowPath", "expectedContentHash", "accepted"],
        "properties": {
            "fieldId": {"type": "string", "minLength": 1},
            "rowPath": {"$ref": "#/components/schemas/RuntimeRowPath"},
            "expectedContentHash": {"$ref": "#/components/schemas/ReviewDigest"},
            "accepted": {"const": True},
        },
    }
    schemas["SubmissionCreateRequest"]["properties"]["reviewDigest"] = {
        "$ref": "#/components/schemas/ReviewDigest"
    }
    schemas["SubmissionCreateRequest"]["properties"]["acknowledgments"]["maxItems"] = 1000
    schemas["SessionMutationResponse"] = {
        "type": "object", "additionalProperties": False,
        "required": ["acceptedRevision", "answers", "validation", "reachablePageIds",
                     "requiredCount", "completedRequiredCount", "invalidInputs"],
        "properties": {
            "acceptedRevision": {"type": "integer", "minimum": 1},
            "answers": {"type": "object", "additionalProperties": True},
            "validation": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
            "reachablePageIds": {"type": "array", "items": {"type": "string"}},
            "requiredCount": {"type": "integer", "minimum": 0},
            "completedRequiredCount": {"type": "integer", "minimum": 0},
            "invalidInputs": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
        },
    }
    schemas["SubmissionReceipt"] = {
        "type": "object", "additionalProperties": False,
        "required": ["receiptId", "submissionId", "message"],
        "properties": {
            "receiptId": {"type": "string"}, "submissionId": {"type": "string"},
            "message": {"type": "string"},
        },
    }
    schemas["SubmissionAttemptStatus"] = {
        "type": "object", "additionalProperties": False,
        "required": ["attemptId", "state"],
        "properties": {
            "attemptId": {"$ref": "#/components/schemas/OpaqueId"},
            "state": {"enum": ["notStarted", "pending", "succeeded", "failed"]},
            "submissionId": {"type": ["string", "null"]},
            "errorCode": {"type": ["string", "null"]},
        },
    }
    # M6 catalog administration is additive to the immutable 4.0.0 collection
    # response. The dedicated catalog paths use a cursor envelope and expose
    # server-derived ownership/settings; no role or workspace claim is accepted
    # in a request body.
    uuid = {"type": "string", "format": "uuid"}
    schemas["CatalogTag"] = {
        "type": "object", "additionalProperties": False,
        "required": ["id", "name"],
        "properties": {"id": uuid, "name": {"type": "string", "minLength": 1, "maxLength": 80},
                       "color": {"type": ["string", "null"], "pattern": "^#[0-9A-Fa-f]{6}$"}},
    }
    schemas["CatalogFolder"] = {
        "type": "object", "additionalProperties": False,
        "required": ["id", "name", "createdAt", "updatedAt"],
        "properties": {"id": uuid, "name": {"type": "string", "minLength": 1, "maxLength": 160},
                       "createdAt": {"type": "string", "format": "date-time"},
                       "updatedAt": {"type": "string", "format": "date-time"}},
    }
    schemas["CatalogNameInput"] = {
        "type": "object", "additionalProperties": False, "required": ["name"],
        "properties": {"name": {"type": "string", "minLength": 1, "maxLength": 160}},
    }
    schemas["CatalogTagInput"] = {
        "type": "object", "additionalProperties": False, "required": ["name"],
        "properties": {"name": {"type": "string", "minLength": 1, "maxLength": 80},
                       "color": {"type": ["string", "null"], "pattern": "^#[0-9A-Fa-f]{6}$"}},
    }
    schemas["CatalogOwner"] = {
        "type": ["object", "null"], "additionalProperties": False,
        "required": ["id", "email"], "properties": {"id": uuid, "email": {"type": "string", "format": "email"}},
    }
    schemas["CatalogForm"] = {
        "type": "object", "additionalProperties": False,
        "required": ["id", "formKey", "title", "status", "revision", "updatedAt", "folderId", "owner", "tags"],
        "properties": {"id": uuid, "formKey": {"type": "string"}, "title": {"type": "string"},
                       "status": {"type": "string"}, "revision": {"type": "integer", "minimum": 1},
                       "updatedAt": {"type": "string", "format": "date-time"}, "folderId": {"anyOf": [uuid, {"type": "null"}]},
                       "owner": {"$ref": "#/components/schemas/CatalogOwner"},
                       "tags": {"type": "array", "items": {"$ref": "#/components/schemas/CatalogTag"}}},
    }
    schemas["CatalogPage"] = {
        "type": "object", "additionalProperties": False, "required": ["items", "nextCursor"],
        "properties": {"items": {"type": "array", "items": {"$ref": "#/components/schemas/CatalogForm"}},
                       "nextCursor": {"type": "string"}},
    }
    schemas["CatalogClassification"] = {
        "type": "object", "additionalProperties": False,
        "properties": {"folderId": {"anyOf": [uuid, {"type": "null"}]},
                       "tagIds": {"type": "array", "uniqueItems": True, "items": uuid}},
    }
    schemas["CatalogTransfer"] = {
        "type": "object", "additionalProperties": False, "required": ["accountId"], "properties": {"accountId": uuid},
    }
    schemas["CatalogSettings"] = {
        "type": "object", "additionalProperties": False, "required": ["workspaceId", "policy", "providers"],
        "properties": {"workspaceId": uuid, "policy": {"type": "object", "additionalProperties": True},
                       "providers": {"type": "object", "additionalProperties": True}},
    }
    schemas["CatalogSettingsInput"] = {
        "type": "object", "additionalProperties": False,
        "properties": {"policy": {"type": "object", "additionalProperties": True},
                       "providers": {"type": "object", "additionalProperties": True}},
    }
    schemas["LiveSessionStartResponse"] = {
        "type": "object", "additionalProperties": False,
        "required": ["sessionId", "respondentSession", "revision", "locale", "runtimeManifest", "release", "expiresAt"],
        "properties": {
            "sessionId": {"type": "string", "format": "uuid"},
            "respondentSession": {"type": "string", "format": "uuid"},
            "revision": {"const": 0}, "locale": {"type": "string"},
            "runtimeManifest": {"type": "object", "additionalProperties": True},
            "release": {"type": "object", "additionalProperties": True},
            "expiresAt": {"type": "string", "format": "date-time"},
        },
    }
    schemas["LiveSessionResponse"] = {
        "type": "object", "additionalProperties": False,
        "required": ["sessionId", "revision", "answers", "status", "runtimeManifest", "definition", "invalidInputs"],
        "properties": {
            "sessionId": {"type": "string", "format": "uuid"},
            "revision": {"type": "integer", "minimum": 0},
            "answers": {"type": "object", "additionalProperties": True},
            "status": {"type": "string"},
            "runtimeManifest": {"type": "object", "additionalProperties": True},
            "definition": {"type": "object", "additionalProperties": True},
            "invalidInputs": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
        },
    }
    schemas["LegacyCapabilityRegistry"] = copy.deepcopy(schemas["CapabilityRegistry"])
    capability = schemas["CapabilityRegistry"]
    capability["required"].extend(["apiContractVersion", "schemaContractVersion", "apiContracts"])
    capability["properties"].update({
        "apiContractVersion": {"const": "4.1.0"},
        "schemaContractVersion": {"const": "4.0.0"},
        "apiContracts": {
            "type": "array",
            "minItems": 2,
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["version", "sha256", "resource"],
                "properties": {
                    "version": {"enum": ["4.0.0", "4.1.0"]},
                    "sha256": {"$ref": "#/components/schemas/Sha256"},
                    "resource": {"type": "string"},
                },
            },
        },
    })
    api["components"] = copy.deepcopy(components["components"])
    rewrite(api)
    catalog_errors = {"400": {"$ref": "#/components/responses/BadRequest"},
                      "401": {"$ref": "#/components/responses/Unauthenticated"},
                      "403": {"$ref": "#/components/responses/Forbidden"},
                      "404": {"$ref": "#/components/responses/NotFound"}}
    def catalog_operation(operation_id: str, summary: str, roles: list[str], response: dict[str, Any], body: str | None = None) -> dict[str, Any]:
        operation = {
            "operationId": operation_id, "summary": summary,
            "x-implementation-status": "implemented",
            "x-authorization": {"roles": roles, "tenantScope": "current-server-workspace-membership"},
            "security": [{"staffCookie": [], "csrfHeader": []}],
            "responses": {"200": response, **catalog_errors},
        }
        if body:
            operation["requestBody"] = {"required": True, "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{body}"}}}}
        return operation
    json_response = lambda schema: {"description": "Successful response.", "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{schema}"}}}}
    workspace_parameter = {"name": "workspace", "in": "path", "required": True, "schema": {"type": "string", "minLength": 1}}
    id_parameter = lambda name: {"name": name, "in": "path", "required": True, "schema": uuid}
    api["paths"]["/v1/workspaces/{workspace}/catalog/forms"] = {
        "parameters": [workspace_parameter],
        "get": {**catalog_operation("m6CatalogSearch", "Search the current workspace form catalog", ["OWNER", "ADMIN", "AUTHOR", "VIEWER"], json_response("CatalogPage")),
                "parameters": [{"name": "q", "in": "query", "schema": {"type": "string", "maxLength": 200}},
                               {"name": "status", "in": "query", "schema": {"type": "string"}},
                               {"name": "owner", "in": "query", "schema": uuid}, {"name": "folder", "in": "query", "schema": uuid},
                               {"name": "tag", "in": "query", "explode": True, "schema": {"type": "array", "items": {"type": "string"}}},
                               {"name": "archived", "in": "query", "schema": {"type": "boolean", "default": False}},
                               {"name": "limit", "in": "query", "schema": {"type": "integer", "minimum": 1, "maximum": 100, "default": 50}},
                               {"name": "cursor", "in": "query", "schema": {"type": "string"}}]},
    }
    api["paths"]["/v1/workspaces/{workspace}/catalog/forms/{form}/duplicate"] = {"parameters": [workspace_parameter, id_parameter("form")], "post": {**catalog_operation("m6CatalogDuplicate", "Duplicate a workspace form", ["OWNER", "ADMINISTRATOR", "AUTHOR"], json_response("CatalogForm")), "responses": {"201": json_response("CatalogForm"), **catalog_errors}}}
    for action, operation_id, roles in (("archive", "m6CatalogArchive", ["OWNER", "ADMINISTRATOR", "AUTHOR"]), ("restore", "m6CatalogRestore", ["OWNER", "ADMINISTRATOR", "AUTHOR"])):
        api["paths"][f"/v1/workspaces/{{workspace}}/catalog/forms/{{form}}/{action}"] = {"parameters": [workspace_parameter, id_parameter("form")], "post": catalog_operation(operation_id, action.capitalize() + " a workspace form", roles, json_response("CatalogForm"))}
    api["paths"]["/v1/workspaces/{workspace}/catalog/forms/{form}/ownership"] = {"parameters": [workspace_parameter, id_parameter("form")], "put": catalog_operation("m6CatalogTransferOwnership", "Transfer form ownership to a current workspace member", ["OWNER", "ADMINISTRATOR"], json_response("CatalogForm"), "CatalogTransfer")}
    api["paths"]["/v1/workspaces/{workspace}/catalog/forms/{form}/classification"] = {"parameters": [workspace_parameter, id_parameter("form")], "put": {**catalog_operation("m6CatalogClassify", "Set form folder and tags", ["OWNER", "ADMINISTRATOR", "AUTHOR"], {"description": "Classification updated."}, "CatalogClassification"), "responses": {"204": {"description": "Classification updated."}, **catalog_errors}}}
    for resource, singular, input_schema, output_schema in (("folders", "folder", "CatalogNameInput", "CatalogFolder"), ("tags", "tag", "CatalogTagInput", "CatalogTag")):
        api["paths"][f"/v1/workspaces/{{workspace}}/{resource}"] = {"parameters": [workspace_parameter],
            "get": catalog_operation(f"m6List{resource.title()}", f"List workspace catalog {resource}", ["OWNER", "ADMIN", "AUTHOR", "VIEWER"], {"description": "Successful response.", "content": {"application/json": {"schema": {"type": "array", "items": {"$ref": f"#/components/schemas/{output_schema}"}}}}}),
            "post": {**catalog_operation(f"m6Create{singular.title()}", f"Create a workspace catalog {singular}", ["OWNER", "ADMINISTRATOR", "AUTHOR"], json_response(output_schema), input_schema), "responses": {"201": json_response(output_schema), **catalog_errors}}}
        api["paths"][f"/v1/workspaces/{{workspace}}/{resource}/{{{singular}}}"] = {"parameters": [workspace_parameter, id_parameter(singular)],
            "patch": catalog_operation(f"m6Update{singular.title()}", f"Update a workspace catalog {singular}", ["OWNER", "ADMINISTRATOR", "AUTHOR"], json_response(output_schema), input_schema),
            "delete": {**catalog_operation(f"m6Delete{singular.title()}", f"Delete a workspace catalog {singular}", ["OWNER", "ADMINISTRATOR", "AUTHOR"], {"description": "Deleted."}), "responses": {"204": {"description": "Deleted."}, **catalog_errors}}}
    api["paths"]["/v1/workspaces/{workspace}/catalog/settings"] = {"parameters": [workspace_parameter],
        "get": catalog_operation("m6EffectiveCatalogSettings", "Read effective policy and provider settings", ["OWNER", "ADMINISTRATOR"], json_response("CatalogSettings")),
        "put": catalog_operation("m6UpdateCatalogSettings", "Update workspace policy and provider overrides", ["OWNER", "ADMINISTRATOR"], json_response("CatalogSettings"), "CatalogSettingsInput")}
    patch = api["paths"]["/v1/sessions/{s}"]["patch"]
    patch["parameters"] = [parameter for parameter in patch["parameters"] if parameter.get("name") == "s"]
    patch["responses"]["200"] = {
        "description": "The accepted canonical typed-session projection.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/SessionMutationResponse"}}},
    }
    patch["requestBody"]["content"]["application/json"]["examples"]["valid"]["value"]["operations"][0]["value"] = {
        "status": "answered", "value": "9007199254740993"
    }
    submit = api["paths"]["/v1/sessions/{s}/submissions"]["post"]
    submit["parameters"] = [parameter for parameter in submit["parameters"] if parameter.get("name") == "s"]
    submit["responses"]["201"] = {
        "description": "The immutable accepted submission receipt.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/SubmissionReceipt"}}},
    }
    submit_example = submit["requestBody"]["content"]["application/json"]["examples"]["valid"]["value"]
    submit_example["reviewDigest"] = "sha256:" + "0" * 64
    submit_example["acknowledgments"] = [{
        "fieldId": "consent", "rowPath": [], "expectedContentHash": "sha256:" + "1" * 64,
        "accepted": True,
    }]
    attempt = api["paths"]["/v1/sessions/{s}/submission-operation"]["get"]
    attempt["parameters"] = [parameter for parameter in attempt["parameters"] if parameter.get("name") == "s"] + [{
        "name": "attemptId", "in": "query", "required": True,
        "schema": {"$ref": "#/components/schemas/OpaqueId"},
    }]
    attempt["responses"]["200"] = {
        "description": "The durable state of the specified submission attempt.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/SubmissionAttemptStatus"}}},
    }
    validate = api["paths"]["/v1/sessions/{s}/validate"]["post"]
    validate["parameters"] = [parameter for parameter in validate["parameters"] if parameter.get("name") == "s"]
    validate.pop("requestBody", None)
    validate["x-implementation-status"] = "implemented"
    validate["responses"]["200"] = {
        "description": "The authoritative validation and review projection.",
        "content": {"application/json": {"schema": {"type": "object", "additionalProperties": True}}},
    }
    for operation_config in (patch, submit, attempt):
        operation_config["x-implementation-status"] = "implemented"
    start = api["paths"]["/v1/public/forms/{shareId}/sessions"]["post"]
    start["parameters"] = [parameter for parameter in start["parameters"]
                           if parameter.get("name") == "shareId"]
    start["requestBody"] = {
        "required": False,
        "content": {"application/json": {"schema": {
            "type": "object", "additionalProperties": False,
            "properties": {"locale": {"type": "string"}, "timeZone": {"type": "string"}},
        }}},
    }
    start["responses"]["201"] = {
        "description": "The unwrapped respondent session bootstrap used by the live route.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/LiveSessionStartResponse"}}},
    }
    start.pop("x-replay", None)
    read_session = api["paths"]["/v1/sessions/{s}"]["get"]
    read_session["parameters"] = [parameter for parameter in read_session["parameters"]
                                  if parameter.get("name") == "s"]
    read_session["responses"]["200"] = {
        "description": "The unwrapped authoritative session projection used by the live route.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/LiveSessionResponse"}}},
    }
    for operation_config in (start, read_session):
        operation_config["x-implementation-status"] = "implemented"
    api["paths"]["/v1/capabilities"]["get"]["responses"]["200"] = {
        "description": "The immutable legacy 4.0.0 capability representation. The additive representation is published at /v1/schemas/capabilities/4.1.0.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/LegacyCapabilityRegistry"}}},
    }

    def encode(value: Any) -> bytes:
        return (HEADER + yaml.safe_dump(value, sort_keys=False, allow_unicode=True)).encode()

    api_bytes = encode(api)
    return {API: api_bytes, COMPONENTS: encode(components), RESOURCE: api_bytes}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[str] = []
    for path, content in generated().items():
        if not path.exists() or path.read_bytes() != content:
            stale.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
    if stale and args.check:
        print("Generated M4 API contract files are stale:", *stale, sep="\n- ")
        return 1
    print("Generated/verified additive M4 API contract 4.1.0; preserved 4.0.0 sources.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
