#!/usr/bin/env python3
"""Generate the additive M4 API contract without changing immutable 4.0.0 bytes."""
from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
LEGACY_API = ROOT / "docs/api/openapi.yaml"
LEGACY_COMPONENTS = ROOT / "docs/contracts/smart-form-builder-lite/4.0.0/openapi-components.yaml"
API = ROOT / "docs/api/openapi-4.1.0.yaml"
COMPONENTS = ROOT / "docs/api/openapi-components-4.1.0.yaml"
RESOURCE = ROOT / "backend/src/main/resources/contracts/openapi-4.1.0.yaml"
HEADER = "# GENERATED by tools/openapi/generate_m4_api_contract.py. DO NOT EDIT.\n"


def operation(op: str, required: list[str], properties: dict[str, Any]) -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["op", "fieldId", *required],
        "properties": {
            "op": {"const": op},
            "fieldId": {"type": "string", "minLength": 1},
            "rowPath": {"$ref": "#/components/schemas/RuntimeRowPath"},
            **properties,
        },
    }


def generated() -> dict[Path, bytes]:
    api = yaml.safe_load(LEGACY_API.read_text(encoding="utf-8"))
    components = yaml.safe_load(LEGACY_COMPONENTS.read_text(encoding="utf-8"))
    api["info"] = copy.deepcopy(api["info"])
    api["info"]["version"] = "4.1.0"
    api["info"]["description"] = (
        "Additive M4 API contract. Canonical package and answer schemas remain 4.0.0; "
        "this API version adds the recursive typed mutation protocol."
    )

    def rewrite(value: Any) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                if key == "$ref" and isinstance(child, str) and child.startswith(
                    "../contracts/smart-form-builder-lite/4.0.0/openapi-components.yaml"
                ):
                    value[key] = child.replace(
                        "../contracts/smart-form-builder-lite/4.0.0/openapi-components.yaml",
                        "./openapi-components-4.1.0.yaml",
                    )
                elif key == "$ref" and isinstance(child, str) and child.startswith(
                    "./openapi-components-4.1.0.yaml#/components/"
                ):
                    value[key] = child.replace("./openapi-components-4.1.0.yaml#/components/", "#/components/")
                elif key == "$ref" and isinstance(child, str) and child.startswith("./") \
                        and ".schema.json" in child:
                    value[key] = "../contracts/smart-form-builder-lite/4.0.0/" + child.removeprefix("./")
                else:
                    rewrite(child)
        elif isinstance(value, list):
            for child in value:
                rewrite(child)

    rewrite(api)
    components["info"]["title"] = "Smart Form Builder Lite 4.1.0 OpenAPI components"
    components["info"]["version"] = "4.1.0"
    rewrite(components)
    schemas = components["components"]["schemas"]
    schemas["RuntimeRowSegment"] = {
        "type": "object",
        "additionalProperties": False,
        "required": ["listFieldId", "itemId"],
        "properties": {
            "listFieldId": {"type": "string", "minLength": 1},
            "itemId": {"$ref": "#/components/schemas/OpaqueId"},
        },
    }
    schemas["RuntimeRowPath"] = {
        "type": "array",
        "maxItems": 3,
        "items": {"$ref": "#/components/schemas/RuntimeRowSegment"},
    }
    input_document = json.loads((ROOT / "docs/contracts/smart-form-builder-lite/4.0.0/input-answer.schema.json")
                                .read_text(encoding="utf-8"))
    input_definitions = input_document.pop("$defs")
    input_document.pop("$schema", None)
    input_document.pop("$id", None)

    def rewrite_input_refs(value: Any) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                if key == "$ref" and child == "#":
                    value[key] = "#/components/schemas/InputAnswerValue"
                elif key == "$ref" and isinstance(child, str) and child.startswith("#/$defs/"):
                    value[key] = "#/components/schemas/InputAnswer_" + child.removeprefix("#/$defs/")
                else:
                    rewrite_input_refs(child)
        elif isinstance(value, list):
            for child in value:
                rewrite_input_refs(child)

    rewrite_input_refs(input_document)
    schemas["InputAnswerValue"] = input_document
    for name, definition in input_definitions.items():
        rewrite_input_refs(definition)
        schemas["InputAnswer_" + name] = definition
    typed_answer = {"$ref": "#/components/schemas/InputAnswerValue"}
    opaque = {"$ref": "#/components/schemas/OpaqueId"}
    schemas["SessionMutation"] = {
        "oneOf": [
            operation("set", ["value"], {"value": typed_answer}),
            operation("clear", [], {}),
            operation("markInvalid", ["reason"], {"reason": {"const": "UNPARSEABLE_INPUT"}}),
            operation(
                "addItem",
                ["itemId"],
                {
                    "itemId": opaque,
                    "initialFields": {
                        "type": "object",
                        "additionalProperties": typed_answer,
                        "default": {},
                    },
                },
            ),
            operation("removeItem", ["itemId"], {"itemId": opaque}),
            operation(
                "moveItem",
                ["itemId"],
                {
                    "itemId": opaque,
                    "beforeItemId": {"anyOf": [opaque, {"type": "null"}]},
                },
            ),
        ],
        "discriminator": {"propertyName": "op"},
    }
    schemas["SessionMutationRequest"]["properties"]["operations"]["maxItems"] = 1000
    schemas["ReviewDigest"] = {"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"}
    schemas["Acknowledgment"] = {
        "type": "object",
        "additionalProperties": False,
        "required": ["fieldId", "rowPath", "expectedContentHash", "accepted"],
        "properties": {
            "fieldId": {"type": "string", "minLength": 1},
            "rowPath": {"$ref": "#/components/schemas/RuntimeRowPath"},
            "expectedContentHash": {"$ref": "#/components/schemas/ReviewDigest"},
            "accepted": {"const": True},
        },
    }
    schemas["SubmissionCreateRequest"]["properties"]["reviewDigest"] = {
        "$ref": "#/components/schemas/ReviewDigest"
    }
    schemas["SubmissionCreateRequest"]["properties"]["acknowledgments"]["maxItems"] = 1000
    schemas["SessionMutationResponse"] = {
        "type": "object", "additionalProperties": False,
        "required": ["acceptedRevision", "answers", "validation", "reachablePageIds",
                     "requiredCount", "completedRequiredCount", "invalidInputs"],
        "properties": {
            "acceptedRevision": {"type": "integer", "minimum": 1},
            "answers": {"type": "object", "additionalProperties": True},
            "validation": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
            "reachablePageIds": {"type": "array", "items": {"type": "string"}},
            "requiredCount": {"type": "integer", "minimum": 0},
            "completedRequiredCount": {"type": "integer", "minimum": 0},
            "invalidInputs": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
        },
    }
    schemas["SubmissionReceipt"] = {
        "type": "object", "additionalProperties": False,
        "required": ["receiptId", "submissionId", "message"],
        "properties": {
            "receiptId": {"type": "string"}, "submissionId": {"type": "string"},
            "message": {"type": "string"},
        },
    }
    schemas["SubmissionAttemptStatus"] = {
        "type": "object", "additionalProperties": False,
        "required": ["attemptId", "state"],
        "properties": {
            "attemptId": {"$ref": "#/components/schemas/OpaqueId"},
            "state": {"enum": ["notStarted", "pending", "succeeded", "failed"]},
            "submissionId": {"type": ["string", "null"]},
            "errorCode": {"type": ["string", "null"]},
        },
    }
    # M6 catalog administration is additive to the immutable 4.0.0 collection
    # response. The dedicated catalog paths use a cursor envelope and expose
    # server-derived ownership/settings; no role or workspace claim is accepted
    # in a request body.
    workspace_roles = [
        "workspace-administrator", "author", "reviewer", "translator", "publisher",
        "response-viewer", "response-exporter", "auditor",
    ]
    catalog_authoring_roles = ["author"]
    workspace_administrator_roles = ["workspace-administrator"]
    for schema_name in ("PermittedWorkspaceChoice", "WorkspaceRole"):
        schemas[schema_name]["properties"]["roles"]["items"] = {"enum": workspace_roles}
    schemas["WorkspaceRoleAssignmentRequest"]["properties"]["roles"]["items"] = {
        "enum": workspace_roles
    }
    schemas["WorkspaceMember"] = {
        "type": "object", "additionalProperties": False,
        "required": ["accountId", "membershipStatus", "roles"],
        "properties": {
            "accountId": {"type": "string", "pattern": "^account-[0-9a-fA-F-]{36}$"},
            "membershipStatus": {"const": "active"},
            "roles": {"type": "array", "minItems": 1, "uniqueItems": True,
                      "items": {"enum": workspace_roles}},
        },
    }
    schemas["WorkspaceMemberCollection"] = {
        "type": "object", "additionalProperties": False,
        "required": ["requestId", "items"],
        "properties": {
            "requestId": {"$ref": "#/components/schemas/OpaqueId"},
            "items": {"type": "array", "items": {"$ref": "#/components/schemas/WorkspaceMember"}},
        },
    }
    uuid = {"type": "string", "format": "uuid"}
    schemas["CatalogTag"] = {
        "type": "object", "additionalProperties": False,
        "required": ["id", "name", "color", "createdAt", "updatedAt"],
        "properties": {"id": uuid, "name": {"type": "string", "minLength": 1, "maxLength": 80},
                       "color": {"type": ["string", "null"], "pattern": "^#[0-9A-Fa-f]{6}$"},
                       "createdAt": {"type": "string", "format": "date-time"}, "updatedAt": {"type": "string", "format": "date-time"}},
    }
    schemas["CatalogFolder"] = {
        "type": "object", "additionalProperties": False,
        "required": ["id", "name", "createdAt", "updatedAt"],
        "properties": {"id": uuid, "name": {"type": "string", "minLength": 1, "maxLength": 160},
                       "createdAt": {"type": "string", "format": "date-time"},
                       "updatedAt": {"type": "string", "format": "date-time"}},
    }
    schemas["CatalogNameInput"] = {
        "type": "object", "additionalProperties": False, "required": ["name"],
        "properties": {"name": {"type": "string", "minLength": 1, "maxLength": 160}},
    }
    schemas["CatalogTagInput"] = {
        "type": "object", "additionalProperties": False, "required": ["name"],
        "properties": {"name": {"type": "string", "minLength": 1, "maxLength": 80},
                       "color": {"type": ["string", "null"], "pattern": "^#[0-9A-Fa-f]{6}$"}},
    }
    schemas["CatalogOwner"] = {
        "type": ["object", "null"], "additionalProperties": False,
        "required": ["id", "email"], "properties": {"id": {"type": "string", "pattern": "^account-[0-9a-fA-F-]{36}$"}, "email": {"type": "string", "format": "email"}},
    }
    schemas["CatalogForm"] = {
        "type": "object", "additionalProperties": False,
        "required": ["id", "formKey", "title", "status", "revision", "updatedAt", "folderId", "owner", "tags"],
        "properties": {"id": uuid, "formKey": {"type": "string"}, "title": {"type": "string"},
                       "status": {"type": "string"}, "revision": {"type": "integer", "minimum": 1},
                       "updatedAt": {"type": "string", "format": "date-time"}, "folderId": {"anyOf": [uuid, {"type": "null"}]},
                       "owner": {"$ref": "#/components/schemas/CatalogOwner"},
                       "tags": {"type": "array", "items": {"$ref": "#/components/schemas/CatalogTag"}}},
    }
    schemas["CatalogPage"] = {
        "type": "object", "additionalProperties": False, "required": ["items", "nextCursor", "catalogRevision"],
        "properties": {"items": {"type": "array", "items": {"$ref": "#/components/schemas/CatalogForm"}},
                       "nextCursor": {"type": "string"}, "catalogRevision": {"type": "integer", "minimum": 0}},
    }
    schemas["CatalogClassification"] = {
        "type": "object", "additionalProperties": False,
        "properties": {"folderId": {"anyOf": [uuid, {"type": "null"}]},
                       "tagIds": {"type": "array", "uniqueItems": True, "items": uuid}},
    }
    schemas["CatalogTransfer"] = {
        "type": "object", "additionalProperties": False, "required": ["accountId"], "properties": {"accountId": {"type": "string", "pattern": "^account-[0-9a-fA-F-]{36}$"}},
    }
    schemas["CatalogSettings"] = {
        "type": "object", "additionalProperties": False, "required": ["workspaceId", "effective", "overrides"],
        "properties": {"workspaceId": {"type": "string", "pattern": "^workspace-[0-9a-fA-F-]{36}$"},
                       "effective": {"type": "object", "additionalProperties": True}, "overrides": {"type": "object", "additionalProperties": True}},
    }
    schemas["CatalogSettingsInput"] = {
        "type": "object", "additionalProperties": False,
        "properties": {"policyOverrides": {"type": "object", "additionalProperties": True},
                       "providerOverrides": {"type": "object", "additionalProperties": True}},
    }
    schemas["LiveSessionStartResponse"] = {
        "type": "object", "additionalProperties": False,
        "required": ["sessionId", "respondentSession", "revision", "locale", "runtimeManifest", "release", "expiresAt"],
        "properties": {
            "sessionId": {"type": "string", "format": "uuid"},
            "respondentSession": {"type": "string", "format": "uuid"},
            "revision": {"const": 0}, "locale": {"type": "string"},
            "runtimeManifest": {"type": "object", "additionalProperties": True},
            "release": {"type": "object", "additionalProperties": True},
            "expiresAt": {"type": "string", "format": "date-time"},
        },
    }
    schemas["LiveSessionResponse"] = {
        "type": "object", "additionalProperties": False,
        "required": ["sessionId", "revision", "answers", "status", "runtimeManifest", "definition", "invalidInputs"],
        "properties": {
            "sessionId": {"type": "string", "format": "uuid"},
            "revision": {"type": "integer", "minimum": 0},
            "answers": {"type": "object", "additionalProperties": True},
            "status": {"type": "string"},
            "runtimeManifest": {"type": "object", "additionalProperties": True},
            "definition": {"type": "object", "additionalProperties": True},
            "invalidInputs": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
        },
    }
    schemas["LegacyCapabilityRegistry"] = copy.deepcopy(schemas["CapabilityRegistry"])
    capability = schemas["CapabilityRegistry"]
    capability["required"].extend(["apiContractVersion", "schemaContractVersion", "apiContracts"])
    capability["properties"].update({
        "apiContractVersion": {"const": "4.1.0"},
        "schemaContractVersion": {"const": "4.0.0"},
        "apiContracts": {
            "type": "array",
            "minItems": 2,
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["version", "sha256", "resource"],
                "properties": {
                    "version": {"enum": ["4.0.0", "4.1.0"]},
                    "sha256": {"$ref": "#/components/schemas/Sha256"},
                    "resource": {"type": "string"},
                },
            },
        },
    })
    api["components"] = copy.deepcopy(components["components"])
    rewrite(api)
    workspace_roles = [
        "workspace-administrator", "author", "reviewer", "translator", "publisher",
        "response-viewer", "response-exporter", "auditor",
    ]

    # M6 identity endpoints are live.  Keep this patch here (rather than hand-editing
    # generated YAML) so the published 4.1 contract remains reproducible.
    def walk_password_rules(value: Any) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                if key in {"password", "newPassword"} and isinstance(child, dict):
                    child["minLength"] = 15
                    child["maxLength"] = 512
                else:
                    walk_password_rules(child)
        elif isinstance(value, list):
            for child in value:
                walk_password_rules(child)

    walk_password_rules(schemas)
    schemas["ActivationRequest"] = {
        "type": "object", "additionalProperties": False,
        "required": ["activationToken", "password", "displayName"],
        "properties": {
            "activationToken": {"type": "string", "minLength": 24},
            "password": {"type": "string", "minLength": 15, "maxLength": 512},
            "displayName": {"type": "string", "minLength": 1, "maxLength": 120},
        },
    }
    schemas["AuthenticatedSession"] = {
        "type": "object", "additionalProperties": False,
        "required": ["safeIdentity", "activationState", "accountStatus", "awaitingSetup", "organizations"],
        "properties": {
            "safeIdentity": {"type": "object", "additionalProperties": False, "required": ["accountId", "username", "displayName"],
                             "properties": {"accountId": {"type": "string", "pattern": "^account-"}, "username": {"type": "string"}, "displayName": {"type": "string"}}},
            "activationState": {"enum": ["active", "pending"]},
            "accountStatus": {"enum": ["active", "suspended"]},
            "awaitingSetup": {"type": "boolean"},
            "organizations": {"type": "array", "items": {"type": "object", "additionalProperties": False,
                "required": ["organizationId", "name", "membershipState", "workspaces"], "properties": {
                    "organizationId": {"type": "string", "pattern": "^organization-"}, "name": {"type": "string"},
                    "membershipState": {"enum": ["active"]}, "workspaces": {"type": "array", "items": {"type": "object", "additionalProperties": False,
                        "required": ["workspaceId", "name", "roles"], "properties": {"workspaceId": {"type": "string", "pattern": "^workspace-"}, "name": {"type": "string"}, "roles": {"type": "array", "items": {"enum": workspace_roles}}}}}}}},
            "currentOrganizationId": {"type": ["string", "null"], "pattern": "^organization-"},
            "currentWorkspaceId": {"type": "string", "pattern": "^workspace-"},
        },
    }
    schemas["BootstrapRequest"] = {
        "type": "object", "additionalProperties": False,
        "required": ["email", "password"],
        "properties": {
            "email": {"type": "string", "format": "email", "maxLength": 254},
            "password": {"type": "string", "minLength": 15, "maxLength": 512},
            "organizationName": {"type": "string", "minLength": 1, "maxLength": 160},
            "workspaceName": {"type": "string", "minLength": 1, "maxLength": 160},
        },
    }
    schemas["BootstrapResponse"] = {
        "type": "object", "additionalProperties": False, "required": ["requestId", "bootstrap"],
        "properties": {"requestId": {"type": "string"}, "bootstrap": {"const": "pending-activation"}},
    }
    parameters = components["components"]["parameters"]
    parameters["BootstrapToken"] = {
        "name": "X-Bootstrap-Token", "in": "header", "required": True,
        "schema": {"type": "string", "minLength": 1},
        "description": "Deployment-provisioned, one-time bootstrap proof. It is consumed atomically and must never be logged.",
    }
    components["components"]["securitySchemes"]["staffCookie"]["name"] = "SI_STAFF_SESSION"
    parameters["LoginCsrfCookie"]["name"] = "SI_LOGIN_CSRF"
    parameters["CsrfCookie"] = {
        "name": "SI_CSRF", "in": "cookie", "required": True,
        "schema": {"type": "string", "minLength": 24},
        "description": "Readable SameSite=Strict CSRF cookie whose value must match X-CSRF-Token for a cookie-authenticated mutation.",
    }
    def rename_cookie_values(value: Any) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                if isinstance(child, str):
                    value[key] = child.replace("smartintake_staff", "SI_STAFF_SESSION").replace("smartintake_login_csrf", "SI_LOGIN_CSRF").replace("smartintake_csrf", "SI_CSRF")
                else:
                    rename_cookie_values(child)
        elif isinstance(value, list):
            for child in value:
                rename_cookie_values(child)
    rename_cookie_values(components)
    api["paths"]["/v1/auth/bootstrap"] = {
        "post": {
            "operationId": "m6Bootstrap", "summary": "Initialize the one-time staff bootstrap owner",
            "x-implementation-status": "implemented",
            "parameters": [{"$ref": "#/components/parameters/BootstrapToken"}],
            "requestBody": {"required": True, "content": {"application/json": {"schema": {"$ref": "#/components/schemas/BootstrapRequest"}}}},
            "responses": {
                "201": {"description": "Pending owner activation created; the proof is returned only in X-Activation-Copy-Link.",
                        "headers": {"X-Activation-Copy-Link": {"schema": {"type": "string"}}},
                        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/BootstrapResponse"}}}},
                "403": {"$ref": "#/components/responses/Forbidden"}, "409": {"$ref": "#/components/responses/Conflict"},
            },
        },
    }
    implemented_identity_paths = [
        "/v1/auth/activate", "/v1/auth/password-change", "/v1/auth/recovery", "/v1/auth/reset",
        "/v1/auth/session", "/v1/auth/sign-in", "/v1/auth/sign-out", "/v1/invitations/accept",
    ]
    for path in implemented_identity_paths:
        for operation_config in api["paths"].get(path, {}).values():
            if isinstance(operation_config, dict) and "responses" in operation_config:
                operation_config["x-implementation-status"] = "implemented"
    for path in ("/v1/auth/sign-out", "/v1/auth/password-change", "/v1/auth/session", "/v1/auth/sign-in"):
        for response in api["paths"][path]["post" if path != "/v1/auth/session" else "get"]["responses"].values():
            if isinstance(response, dict):
                response.pop("headers", None)
    sign_out = api["paths"]["/v1/auth/sign-out"]["post"]
    sign_out.pop("requestBody", None)
    sign_out["responses"]["204"] = {"description": "Revokes the current cookie session and expires staff and CSRF cookies."}
    implemented_admin_mutations = {
        ("/v1/organizations/{o}/users", "post"), ("/v1/organizations/{o}/users/{u}", "patch"),
        ("/v1/organizations/{o}/users/{u}", "delete"), ("/v1/organizations/{o}/users/{u}/invitations", "post"),
        ("/v1/organizations/{o}/invitations/{i}", "delete"), ("/v1/organizations/{o}/users/{u}/recovery", "post"),
        ("/v1/platform/organizations", "post"), ("/v1/platform/organizations/{o}", "patch"),
        ("/v1/platform/organizations/{o}/users", "post"), ("/v1/platform/accounts/{a}", "patch"),
        ("/v1/platform/accounts/{a}/recovery", "post"), ("/v1/workspaces/{w}/users/{u}/roles", "put"),
        ("/v1/workspaces/{w}/users/{u}/roles", "delete"),
    }
    revisioned_admin_mutations = {
        ("/v1/organizations/{o}/users/{u}", "patch"), ("/v1/organizations/{o}/users/{u}", "delete"),
        ("/v1/organizations/{o}/invitations/{i}", "delete"), ("/v1/platform/organizations/{o}", "patch"),
        ("/v1/platform/accounts/{a}", "patch"), ("/v1/workspaces/{w}/users/{u}/roles", "put"),
        ("/v1/workspaces/{w}/users/{u}/roles", "delete"),
    }
    for path, method in implemented_admin_mutations:
        admin = api["paths"][path][method]
        admin["x-implementation-status"] = "implemented"
        admin["x-replay"] = ("Idempotency-Key is durably scoped to actor, tenant/account scope, operation and canonical request digest for at least seven days; "
                             "equal requests replay the original status, body and ETag, while changed-request reuse is 409. "
                             "Secret capability-copy headers are delivered only once and are omitted from replays.")
        if (path, method) in revisioned_admin_mutations:
            parameters = admin.setdefault("parameters", [])
            if not any(parameter.get("$ref", "").endswith("/IfMatch") for parameter in parameters):
                parameters.append({"$ref": "#/components/parameters/IfMatch"})
            admin["x-concurrency"] = "Strong ETag and If-Match are required; missing is 428, stale is 412."
            admin["responses"]["412"] = {"$ref": "#/components/responses/PreconditionFailed"}
            admin["responses"]["428"] = {"$ref": "#/components/responses/PreconditionRequired"}
    catalog_errors = {"400": {"$ref": "#/components/responses/BadRequest"},
                      "401": {"$ref": "#/components/responses/Unauthenticated"},
                      "403": {"$ref": "#/components/responses/Forbidden"},
                      "404": {"$ref": "#/components/responses/NotFound"}}
    def catalog_operation(operation_id: str, summary: str, roles: list[str], response: dict[str, Any], body: str | None = None,
                          state_changing: bool = False) -> dict[str, Any]:
        operation = {
            "operationId": operation_id, "summary": summary,
            "x-implementation-status": "implemented",
            "x-authorization": {"roles": roles, "tenantScope": "current-server-workspace-membership"},
            "security": [{"staffCookie": [], **({"csrfHeader": []} if state_changing else {})}],
            "responses": {"200": response, **catalog_errors},
        }
        if body:
            operation["requestBody"] = {"required": True, "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{body}"}}}}
        return operation
    json_response = lambda schema: {"description": "Successful response.", "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{schema}"}}}}
    workspace_parameter = {"name": "workspace", "in": "path", "required": True, "schema": {"type": "string", "pattern": "^workspace-[0-9a-fA-F-]{36}$"}}
    api["paths"].pop("/v1/workspaces/{w}/folders", None)
    api["paths"].pop("/v1/workspaces/{w}/tags", None)
    id_parameter = lambda name: {"name": name, "in": "path", "required": True, "schema": uuid}
    api["paths"]["/v1/workspaces/{workspace}/catalog/forms"] = {
        "parameters": [workspace_parameter],
        "get": {**catalog_operation("m6CatalogSearch", "Search the current workspace form catalog", workspace_roles, json_response("CatalogPage")),
                "parameters": [{"name": "q", "in": "query", "schema": {"type": "string", "maxLength": 200}},
                               {"name": "status", "in": "query", "schema": {"type": "string"}},
                               {"name": "owner", "in": "query", "schema": uuid}, {"name": "folder", "in": "query", "schema": uuid},
                               {"name": "tag", "in": "query", "explode": True, "schema": {"type": "array", "items": {"type": "string"}}},
                               {"name": "archived", "in": "query", "schema": {"type": "boolean", "default": False}},
                               {"name": "limit", "in": "query", "schema": {"type": "integer", "minimum": 1, "maximum": 100, "default": 50}},
                               {"name": "cursor", "in": "query", "schema": {"type": "string"}}]},
    }
    api["paths"]["/v1/workspaces/{workspace}/catalog/forms/{form}/duplicate"] = {"parameters": [workspace_parameter, id_parameter("form")], "post": {**catalog_operation("m6CatalogDuplicate", "Duplicate a workspace form", catalog_authoring_roles, json_response("CatalogForm"), state_changing=True), "responses": {"201": json_response("CatalogForm"), **catalog_errors}}}
    for action, operation_id in (("archive", "m6CatalogArchive"), ("restore", "m6CatalogRestore")):
        api["paths"][f"/v1/workspaces/{{workspace}}/catalog/forms/{{form}}/{action}"] = {"parameters": [workspace_parameter, id_parameter("form")], "post": catalog_operation(operation_id, action.capitalize() + " a workspace form", catalog_authoring_roles, json_response("CatalogForm"), state_changing=True)}
    api["paths"]["/v1/workspaces/{workspace}/catalog/forms/{form}/ownership"] = {"parameters": [workspace_parameter, id_parameter("form")], "put": catalog_operation("m6CatalogTransferOwnership", "Transfer form ownership to a current workspace member", workspace_administrator_roles, json_response("CatalogForm"), "CatalogTransfer", state_changing=True)}
    api["paths"]["/v1/workspaces/{workspace}/catalog/forms/{form}/classification"] = {"parameters": [workspace_parameter, id_parameter("form")], "put": {**catalog_operation("m6CatalogClassify", "Set form folder and tags", catalog_authoring_roles, {"description": "Classification updated."}, "CatalogClassification", state_changing=True), "responses": {"204": {"description": "Classification updated."}, **catalog_errors}}}
    for resource, singular, input_schema, output_schema in (("folders", "folder", "CatalogNameInput", "CatalogFolder"), ("tags", "tag", "CatalogTagInput", "CatalogTag")):
        api["paths"][f"/v1/workspaces/{{workspace}}/{resource}"] = {"parameters": [workspace_parameter],
            "get": catalog_operation(f"m6List{resource.title()}", f"List workspace catalog {resource}", workspace_roles, {"description": "Successful response.", "content": {"application/json": {"schema": {"type": "array", "items": {"$ref": f"#/components/schemas/{output_schema}"}}}}}),
            "post": {**catalog_operation(f"m6Create{singular.title()}", f"Create a workspace catalog {singular}", catalog_authoring_roles, json_response(output_schema), input_schema, state_changing=True), "responses": {"201": json_response(output_schema), **catalog_errors}}}
        api["paths"][f"/v1/workspaces/{{workspace}}/{resource}/{{{singular}}}"] = {"parameters": [workspace_parameter, id_parameter(singular)],
            "patch": catalog_operation(f"m6Update{singular.title()}", f"Update a workspace catalog {singular}", catalog_authoring_roles, json_response(output_schema), input_schema, state_changing=True),
            "delete": {**catalog_operation(f"m6Delete{singular.title()}", f"Delete a workspace catalog {singular}", catalog_authoring_roles, {"description": "Deleted."}, state_changing=True), "responses": {"204": {"description": "Deleted."}, **catalog_errors}}}
    api["paths"]["/v1/workspaces/{workspace}/catalog/settings"] = {"parameters": [workspace_parameter],
        "get": catalog_operation("m6EffectiveCatalogSettings", "Read effective policy and provider settings", workspace_administrator_roles, json_response("CatalogSettings")),
        "put": catalog_operation("m6UpdateCatalogSettings", "Update workspace policy and provider overrides", workspace_administrator_roles, json_response("CatalogSettings"), "CatalogSettingsInput", state_changing=True)}
    api["paths"]["/v1/workspaces/{workspace}/members"] = {
        "parameters": [workspace_parameter],
        "get": catalog_operation("m6ListWorkspaceMembers", "List transferable current workspace members",
                                 workspace_administrator_roles, json_response("WorkspaceMemberCollection")),
    }
    patch = api["paths"]["/v1/sessions/{s}"]["patch"]
    patch["parameters"] = [parameter for parameter in patch["parameters"] if parameter.get("name") == "s"]
    patch["responses"]["200"] = {
        "description": "The accepted canonical typed-session projection.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/SessionMutationResponse"}}},
    }
    patch["requestBody"]["content"]["application/json"]["examples"]["valid"]["value"]["operations"][0]["value"] = {
        "status": "answered", "value": "9007199254740993"
    }
    submit = api["paths"]["/v1/sessions/{s}/submissions"]["post"]
    submit["parameters"] = [parameter for parameter in submit["parameters"] if parameter.get("name") == "s"]
    submit["responses"]["201"] = {
        "description": "The immutable accepted submission receipt.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/SubmissionReceipt"}}},
    }
    submit_example = submit["requestBody"]["content"]["application/json"]["examples"]["valid"]["value"]
    submit_example["reviewDigest"] = "sha256:" + "0" * 64
    submit_example["acknowledgments"] = [{
        "fieldId": "consent", "rowPath": [], "expectedContentHash": "sha256:" + "1" * 64,
        "accepted": True,
    }]
    attempt = api["paths"]["/v1/sessions/{s}/submission-operation"]["get"]
    attempt["parameters"] = [parameter for parameter in attempt["parameters"] if parameter.get("name") == "s"] + [{
        "name": "attemptId", "in": "query", "required": True,
        "schema": {"$ref": "#/components/schemas/OpaqueId"},
    }]
    attempt["responses"]["200"] = {
        "description": "The durable state of the specified submission attempt.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/SubmissionAttemptStatus"}}},
    }
    validate = api["paths"]["/v1/sessions/{s}/validate"]["post"]
    validate["parameters"] = [parameter for parameter in validate["parameters"] if parameter.get("name") == "s"]
    validate.pop("requestBody", None)
    validate["x-implementation-status"] = "implemented"
    validate["responses"]["200"] = {
        "description": "The authoritative validation and review projection.",
        "content": {"application/json": {"schema": {"type": "object", "additionalProperties": True}}},
    }
    for operation_config in (patch, submit, attempt):
        operation_config["x-implementation-status"] = "implemented"
    # The live draft controller uses the canonical form UUID as its draft ID and
    # returns its maps unwrapped.  Do not inherit the old planned M2 envelope or
    # generic mutation replay metadata for this optimistic-concurrency endpoint.
    draft_path = api["paths"]["/v1/workspaces/{w}/forms/{f}/drafts/{d}"]
    schemas["LiveDraftRead"] = {
        "type": "object", "additionalProperties": False,
        "required": ["id", "revision", "definition", "diagnostics"],
        "properties": {"id": {"type": "string", "format": "uuid"}, "revision": {"type": "integer", "minimum": 1},
                       "definition": {"type": "object"}, "diagnostics": {"type": "array", "items": {}}},
    }
    schemas["LiveDraftWrite"] = {
        "type": "object", "additionalProperties": False,
        "required": ["revision", "definition", "diagnostics"],
        "properties": {"revision": {"type": "integer", "minimum": 1}, "definition": {"type": "object"},
                       "diagnostics": {"type": "array", "items": {}}},
    }
    draft_read_example = {"id": "11111111-1111-1111-1111-111111111111", "revision": 3,
                          "definition": {"formKey": "intake"}, "diagnostics": []}
    draft_write_example = {"revision": 4, "definition": {"formKey": "intake"}, "diagnostics": []}
    for method, schema in (("get", "LiveDraftRead"), ("put", "LiveDraftWrite")):
        operation_config = draft_path[method]
        operation_config["x-implementation-status"] = "implemented"
        operation_config["description"] = "Live canonical UUID draft endpoint; responses are unwrapped."
        operation_config["responses"]["200"] = {"description": "Unwrapped live draft response.",
            "headers": {"ETag": {"$ref": "#/components/headers/ETag"}},
            "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{schema}"},
                                                "example": draft_read_example if method == "get" else draft_write_example}}}
        operation_config.pop("x-replay", None)
    draft_parameters = [
        {"name": "w", "in": "path", "required": True, "schema": {"$ref": "#/components/schemas/OpaqueId"}},
        {"name": "f", "in": "path", "required": True, "schema": {"$ref": "#/components/schemas/OpaqueId"}},
        {"name": "d", "in": "path", "required": True, "schema": {"type": "string", "format": "uuid"}},
    ]
    draft_path["get"]["parameters"] = draft_parameters
    draft_path["put"]["parameters"] = draft_parameters + [{"$ref": "#/components/parameters/IfMatch"}]
    draft_path["put"]["requestBody"] = {"required": True, "content": {"application/json": {"schema": {
        "type": "object", "additionalProperties": False, "required": ["definition"],
        "properties": {"definition": {"type": "object"}}}, "example": {"definition": {"formKey": "intake"}}}}}
    headers = components["components"].setdefault("headers", {})
    for name, description in {
        "X-Temporary-Password-Copy": "Authorized one-time temporary password delivery. Never log or persist this value.",
        "X-Invitation-Copy-Link": "Authorized one-time invitation delivery link. Never log or persist this value.",
        "X-Recovery-Copy-Link": "Authorized one-time recovery delivery link. Never log or persist this value.",
        "X-Activation-Copy-Link": "Authorized one-time activation delivery link. Never log or persist this value.",
    }.items():
        headers[name] = {"description": description, "schema": {"type": "string"}}
    def copy_header(path: str, method: str, status: str, name: str) -> None:
        operation = api["paths"].get(path, {}).get(method)
        if operation is not None:
            operation.setdefault("responses", {}).setdefault(status, {"description": "Successful response."}) \
                .setdefault("headers", {})[name] = {"$ref": f"#/components/headers/{name}"}
    copy_header("/v1/organizations/{o}/users", "post", "201", "X-Temporary-Password-Copy")
    copy_header("/v1/organizations/{o}/users", "post", "201", "X-Activation-Copy-Link")
    copy_header("/v1/platform/organizations/{o}/users", "post", "201", "X-Temporary-Password-Copy")
    copy_header("/v1/platform/organizations/{o}/users", "post", "201", "X-Activation-Copy-Link")
    copy_header("/v1/organizations/{o}/users/{u}/invitations", "post", "201", "X-Invitation-Copy-Link")
    copy_header("/v1/organizations/{o}/users/{u}/recovery", "post", "201", "X-Recovery-Copy-Link")
    copy_header("/v1/platform/accounts/{a}/recovery", "post", "201", "X-Recovery-Copy-Link")
    copy_header("/v1/auth/bootstrap", "post", "201", "X-Activation-Copy-Link")
    start = api["paths"]["/v1/public/forms/{shareId}/sessions"]["post"]
    start["parameters"] = [parameter for parameter in start["parameters"]
                           if parameter.get("name") == "shareId"]
    start["requestBody"] = {
        "required": False,
        "content": {"application/json": {"schema": {
            "type": "object", "additionalProperties": False,
            "properties": {"locale": {"type": "string"}, "timeZone": {"type": "string"}},
        }}},
    }
    start["responses"]["201"] = {
        "description": "The unwrapped respondent session bootstrap used by the live route.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/LiveSessionStartResponse"}}},
    }
    start.pop("x-replay", None)
    read_session = api["paths"]["/v1/sessions/{s}"]["get"]
    read_session["parameters"] = [parameter for parameter in read_session["parameters"]
                                  if parameter.get("name") == "s"]
    read_session["responses"]["200"] = {
        "description": "The unwrapped authoritative session projection used by the live route.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/LiveSessionResponse"}}},
    }
    for operation_config in (start, read_session):
        operation_config["x-implementation-status"] = "implemented"
    api["paths"]["/v1/capabilities"]["get"]["responses"]["200"] = {
        "description": "The immutable legacy 4.0.0 capability representation. The additive representation is published at /v1/schemas/capabilities/4.1.0.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/LegacyCapabilityRegistry"}}},
    }

    # Cookie-authenticated reads do not require a CSRF proof. Every non-GET
    # cookie-authenticated operation does, including the additive catalog and
    # workspace-member routes above. Keep this method-derived so later 4.1
    # additions cannot accidentally publish the wrong browser security contract.
    for path_item in api["paths"].values():
        for method, operation_config in path_item.items():
            if not isinstance(operation_config, dict) or method not in {"get", "post", "put", "patch", "delete"}:
                continue
            security = operation_config.get("security", [])
            if any("staffCookie" in requirement for requirement in security):
                operation_config["security"] = [{"staffCookie": [], **({} if method == "get" else {"csrfHeader": []})}]

    # `api` receives a deep copy before the M6 schema patches above. Refresh it
    # immediately before serialization so the monolithic published/backend copies
    # remain byte-for-byte aligned with the generated components document.
    api["components"] = copy.deepcopy(components["components"])

    def encode(value: Any) -> bytes:
        return (HEADER + yaml.safe_dump(value, sort_keys=False, allow_unicode=True)).encode()

    api_bytes = encode(api)
    return {API: api_bytes, COMPONENTS: encode(components), RESOURCE: api_bytes}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[str] = []
    for path, content in generated().items():
        if not path.exists() or path.read_bytes() != content:
            stale.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
    if stale and args.check:
        print("Generated M4 API contract files are stale:", *stale, sep="\n- ")
        return 1
    print("Generated/verified additive M4 API contract 4.1.0; preserved 4.0.0 sources.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
