#!/usr/bin/env python3
"""Generate the additive M4 API contract without changing immutable 4.0.0 bytes."""
from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
LEGACY_API = ROOT / "docs/api/openapi.yaml"
LEGACY_COMPONENTS = ROOT / "docs/contracts/smart-form-builder-lite/4.0.0/openapi-components.yaml"
API = ROOT / "docs/api/openapi-4.1.0.yaml"
COMPONENTS = ROOT / "docs/api/openapi-components-4.1.0.yaml"
RESOURCE = ROOT / "backend/src/main/resources/contracts/openapi-4.1.0.yaml"
HEADER = "# GENERATED by tools/openapi/generate_m4_api_contract.py. DO NOT EDIT.\n"


def operation(op: str, required: list[str], properties: dict[str, Any]) -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["op", "fieldId", *required],
        "properties": {
            "op": {"const": op},
            "fieldId": {"type": "string", "minLength": 1},
            "rowPath": {"$ref": "#/components/schemas/RuntimeRowPath"},
            **properties,
        },
    }


def generated() -> dict[Path, bytes]:
    api = yaml.safe_load(LEGACY_API.read_text(encoding="utf-8"))
    components = yaml.safe_load(LEGACY_COMPONENTS.read_text(encoding="utf-8"))
    api["info"] = copy.deepcopy(api["info"])
    api["info"]["version"] = "4.1.0"
    api["info"]["description"] = (
        "Additive M4 API contract. Canonical package and answer schemas remain 4.0.0; "
        "this API version adds the recursive typed mutation protocol."
    )

    def rewrite(value: Any) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                if key == "$ref" and isinstance(child, str) and child.startswith(
                    "../contracts/smart-form-builder-lite/4.0.0/openapi-components.yaml"
                ):
                    value[key] = child.replace(
                        "../contracts/smart-form-builder-lite/4.0.0/openapi-components.yaml",
                        "./openapi-components-4.1.0.yaml",
                    )
                elif key == "$ref" and isinstance(child, str) and child.startswith(
                    "./openapi-components-4.1.0.yaml#/components/"
                ):
                    value[key] = child.replace("./openapi-components-4.1.0.yaml#/components/", "#/components/")
                elif key == "$ref" and isinstance(child, str) and child.startswith("./") \
                        and ".schema.json" in child:
                    value[key] = "../contracts/smart-form-builder-lite/4.0.0/" + child.removeprefix("./")
                else:
                    rewrite(child)
        elif isinstance(value, list):
            for child in value:
                rewrite(child)

    rewrite(api)
    components["info"]["title"] = "Smart Form Builder Lite 4.1.0 OpenAPI components"
    components["info"]["version"] = "4.1.0"
    rewrite(components)
    schemas = components["components"]["schemas"]
    schemas["RuntimeRowSegment"] = {
        "type": "object",
        "additionalProperties": False,
        "required": ["listFieldId", "itemId"],
        "properties": {
            "listFieldId": {"type": "string", "minLength": 1},
            "itemId": {"$ref": "#/components/schemas/OpaqueId"},
        },
    }
    schemas["RuntimeRowPath"] = {
        "type": "array",
        "maxItems": 3,
        "items": {"$ref": "#/components/schemas/RuntimeRowSegment"},
    }
    input_document = json.loads((ROOT / "docs/contracts/smart-form-builder-lite/4.0.0/input-answer.schema.json")
                                .read_text(encoding="utf-8"))
    input_definitions = input_document.pop("$defs")
    input_document.pop("$schema", None)
    input_document.pop("$id", None)

    def rewrite_input_refs(value: Any) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                if key == "$ref" and child == "#":
                    value[key] = "#/components/schemas/InputAnswerValue"
                elif key == "$ref" and isinstance(child, str) and child.startswith("#/$defs/"):
                    value[key] = "#/components/schemas/InputAnswer_" + child.removeprefix("#/$defs/")
                else:
                    rewrite_input_refs(child)
        elif isinstance(value, list):
            for child in value:
                rewrite_input_refs(child)

    rewrite_input_refs(input_document)
    schemas["InputAnswerValue"] = input_document
    for name, definition in input_definitions.items():
        rewrite_input_refs(definition)
        schemas["InputAnswer_" + name] = definition
    typed_answer = {"$ref": "#/components/schemas/InputAnswerValue"}
    opaque = {"$ref": "#/components/schemas/OpaqueId"}
    schemas["SessionMutation"] = {
        "oneOf": [
            operation("set", ["value"], {"value": typed_answer}),
            operation("clear", [], {}),
            operation("markInvalid", ["reason"], {"reason": {"const": "UNPARSEABLE_INPUT"}}),
            operation(
                "addItem",
                ["itemId"],
                {
                    "itemId": opaque,
                    "initialFields": {
                        "type": "object",
                        "additionalProperties": typed_answer,
                        "default": {},
                    },
                },
            ),
            operation("removeItem", ["itemId"], {"itemId": opaque}),
            operation(
                "moveItem",
                ["itemId"],
                {
                    "itemId": opaque,
                    "beforeItemId": {"anyOf": [opaque, {"type": "null"}]},
                },
            ),
        ],
        "discriminator": {"propertyName": "op"},
    }
    schemas["SessionMutationRequest"]["properties"]["operations"]["maxItems"] = 1000
    schemas["ReviewDigest"] = {"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"}
    schemas["Acknowledgment"] = {
        "type": "object",
        "additionalProperties": False,
        "required": ["fieldId", "rowPath", "expectedContentHash", "accepted"],
        "properties": {
            "fieldId": {"type": "string", "minLength": 1},
            "rowPath": {"$ref": "#/components/schemas/RuntimeRowPath"},
            "expectedContentHash": {"$ref": "#/components/schemas/ReviewDigest"},
            "accepted": {"const": True},
        },
    }
    schemas["SubmissionCreateRequest"]["properties"]["reviewDigest"] = {
        "$ref": "#/components/schemas/ReviewDigest"
    }
    schemas["SubmissionCreateRequest"]["properties"]["acknowledgments"]["maxItems"] = 1000
    schemas["SessionMutationResponse"] = {
        "type": "object", "additionalProperties": False,
        "required": ["acceptedRevision", "answers", "validation", "reachablePageIds",
                     "requiredCount", "completedRequiredCount", "invalidInputs"],
        "properties": {
            "acceptedRevision": {"type": "integer", "minimum": 1},
            "answers": {"type": "object", "additionalProperties": True},
            "validation": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
            "reachablePageIds": {"type": "array", "items": {"type": "string"}},
            "requiredCount": {"type": "integer", "minimum": 0},
            "completedRequiredCount": {"type": "integer", "minimum": 0},
            "invalidInputs": {"type": "array", "items": {"type": "object", "additionalProperties": True}},
        },
    }
    schemas["SubmissionReceipt"] = {
        "type": "object", "additionalProperties": False,
        "required": ["receiptId", "submissionId", "message"],
        "properties": {
            "receiptId": {"type": "string"}, "submissionId": {"type": "string"},
            "message": {"type": "string"},
        },
    }
    schemas["SubmissionAttemptStatus"] = {
        "type": "object", "additionalProperties": False,
        "required": ["attemptId", "state"],
        "properties": {
            "attemptId": {"$ref": "#/components/schemas/OpaqueId"},
            "state": {"enum": ["notStarted", "pending", "succeeded", "failed"]},
            "submissionId": {"type": ["string", "null"]},
            "errorCode": {"type": ["string", "null"]},
        },
    }
    schemas["LegacyCapabilityRegistry"] = copy.deepcopy(schemas["CapabilityRegistry"])
    capability = schemas["CapabilityRegistry"]
    capability["required"].extend(["apiContractVersion", "schemaContractVersion", "apiContracts"])
    capability["properties"].update({
        "apiContractVersion": {"const": "4.1.0"},
        "schemaContractVersion": {"const": "4.0.0"},
        "apiContracts": {
            "type": "array",
            "minItems": 2,
            "items": {
                "type": "object",
                "additionalProperties": False,
                "required": ["version", "sha256", "resource"],
                "properties": {
                    "version": {"enum": ["4.0.0", "4.1.0"]},
                    "sha256": {"$ref": "#/components/schemas/Sha256"},
                    "resource": {"type": "string"},
                },
            },
        },
    })
    api["components"] = copy.deepcopy(components["components"])
    rewrite(api)
    patch = api["paths"]["/v1/sessions/{s}"]["patch"]
    patch["parameters"] = [parameter for parameter in patch["parameters"] if parameter.get("name") == "s"]
    patch["responses"]["200"] = {
        "description": "The accepted canonical typed-session projection.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/SessionMutationResponse"}}},
    }
    patch["requestBody"]["content"]["application/json"]["examples"]["valid"]["value"]["operations"][0]["value"] = {
        "status": "answered", "value": "9007199254740993"
    }
    submit = api["paths"]["/v1/sessions/{s}/submissions"]["post"]
    submit["parameters"] = [parameter for parameter in submit["parameters"] if parameter.get("name") == "s"]
    submit["responses"]["201"] = {
        "description": "The immutable accepted submission receipt.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/SubmissionReceipt"}}},
    }
    submit_example = submit["requestBody"]["content"]["application/json"]["examples"]["valid"]["value"]
    submit_example["reviewDigest"] = "sha256:" + "0" * 64
    submit_example["acknowledgments"] = [{
        "fieldId": "consent", "rowPath": [], "expectedContentHash": "sha256:" + "1" * 64,
        "accepted": True,
    }]
    attempt = api["paths"]["/v1/sessions/{s}/submission-operation"]["get"]
    attempt["parameters"] = [parameter for parameter in attempt["parameters"] if parameter.get("name") == "s"] + [{
        "name": "attemptId", "in": "query", "required": True,
        "schema": {"$ref": "#/components/schemas/OpaqueId"},
    }]
    attempt["responses"]["200"] = {
        "description": "The durable state of the specified submission attempt.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/SubmissionAttemptStatus"}}},
    }
    validate = api["paths"]["/v1/sessions/{s}/validate"]["post"]
    validate["parameters"] = [parameter for parameter in validate["parameters"] if parameter.get("name") == "s"]
    validate.pop("requestBody", None)
    validate["x-implementation-status"] = "implemented"
    validate["responses"]["200"] = {
        "description": "The authoritative validation and review projection.",
        "content": {"application/json": {"schema": {"type": "object", "additionalProperties": True}}},
    }
    for operation_config in (patch, submit, attempt):
        operation_config["x-implementation-status"] = "implemented"
    api["paths"]["/v1/capabilities"]["get"]["responses"]["200"] = {
        "description": "The immutable legacy 4.0.0 capability representation. The additive representation is published at /v1/schemas/capabilities/4.1.0.",
        "content": {"application/json": {"schema": {"$ref": "#/components/schemas/LegacyCapabilityRegistry"}}},
    }

    def encode(value: Any) -> bytes:
        return (HEADER + yaml.safe_dump(value, sort_keys=False, allow_unicode=True)).encode()

    api_bytes = encode(api)
    return {API: api_bytes, COMPONENTS: encode(components), RESOURCE: api_bytes}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[str] = []
    for path, content in generated().items():
        if not path.exists() or path.read_bytes() != content:
            stale.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
    if stale and args.check:
        print("Generated M4 API contract files are stale:", *stale, sep="\n- ")
        return 1
    print("Generated/verified additive M4 API contract 4.1.0; preserved 4.0.0 sources.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
