package com.kodeboxx.smartintake;

import java.util.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.context.*; import org.springframework.boot.test.web.client.*; import org.springframework.boot.test.web.server.LocalServerPort; import org.springframework.http.*; import org.springframework.jdbc.core.JdbcTemplate; import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
class SecurityLifecycleIntegrationTests {
 @LocalServerPort int port; @Autowired TestRestTemplate http; @Autowired JdbcTemplate db; UUID form, session; String staff, respondent;
 String u(String p){return "http://localhost:"+port+"/v1"+p;} HttpHeaders staff(){HttpHeaders h=new HttpHeaders();h.set("X-Staff-Session",staff);return h;} @BeforeEach void seed(){UUID account=UUID.randomUUID(),org=UUID.randomUUID(),ws=UUID.randomUUID(),release=UUID.randomUUID();form=UUID.randomUUID();session=UUID.randomUUID();staff=UUID.randomUUID().toString();respondent=UUID.randomUUID().toString();db.update("insert into accounts(id,email,password_hash) values(?,?,?)",account,"test"+account+"@example.test","hash");db.update("insert into organizations(id,name) values(?,?)",org,"Test");db.update("insert into workspaces(id,organization_id,workspace_key,name) values(?,?,?,?)",ws,org,"test-"+account,"Test");db.update("insert into memberships(account_id,workspace_id,role) values(?,?,?)",account,ws,"OWNER");db.update("insert into staff_sessions(token,account_id,expires_at) values(?,?,now()+interval '1 hour')",UUID.fromString(staff),account);String def="{\"contractVersion\":\"4.0.0\",\"pages\":[]}";db.update("insert into forms(id,workspace_id,form_key,title,definition) values(?,?,?,?,cast(? as jsonb))",form,ws,"form-"+form,"Test",def);db.update("insert into form_releases(id,form_id,version,package) values(?,?,1,cast(? as jsonb))",release,form,def);db.update("insert into sessions(id,form_id,release_id,respondent_token,answers) values(?,?,?,?,cast('{}' as jsonb))",session,form,release,UUID.fromString(respondent));}
 @Test void anonymousStaffAndWrongWorkspaceAreDenied(){assertEquals(HttpStatus.UNAUTHORIZED,http.getForEntity(u("/workspaces/x/forms"),String.class).getStatusCode());assertEquals(HttpStatus.UNAUTHORIZED,http.exchange(u("/workspaces/wrong/forms"),HttpMethod.GET,new HttpEntity<>(staff()),String.class).getStatusCode());}
 @Test void missingAndWrongRespondentTokensAreDenied(){assertEquals(HttpStatus.UNAUTHORIZED,http.getForEntity(u("/sessions/"+session),String.class).getStatusCode());HttpHeaders h=new HttpHeaders();h.set("X-Respondent-Session",UUID.randomUUID().toString());assertEquals(HttpStatus.UNAUTHORIZED,http.exchange(u("/sessions/"+session),HttpMethod.GET,new HttpEntity<>(h),String.class).getStatusCode());}
 @Test void unauthorizedExportIsDenied(){assertEquals(HttpStatus.UNAUTHORIZED,http.getForEntity(u("/workspaces/x/exports.csv"),String.class).getStatusCode());}
 @Test void authorizedRespondentReadsPinnedRelease(){HttpHeaders h=new HttpHeaders();h.set("X-Respondent-Session",respondent);ResponseEntity<String> r=http.exchange(u("/sessions/"+session),HttpMethod.GET,new HttpEntity<>(h),String.class);assertEquals(HttpStatus.OK,r.getStatusCode());assertTrue(r.getBody().contains("4.0.0"));assertNotNull(db.queryForObject("select respondent_secret_sha256 from sessions where id=?",String.class,session));}
 @Test void crossWorkspaceSubmissionDetailIsDenied(){UUID submission=UUID.randomUUID();db.update("insert into submissions(id,form_id,session_id,envelope) values(?,?,?,cast(? as jsonb))",submission,form,session,"{}");ResponseEntity<String> r=http.exchange(u("/workspaces/not-owned/submissions/"+submission),HttpMethod.GET,new HttpEntity<>(staff()),String.class);assertEquals(HttpStatus.UNAUTHORIZED,r.getStatusCode());}
 @Test void publishedSessionStaysPinnedAfterDraftMutation(){String changed="{\"contractVersion\":\"4.0.0\",\"title\":\"MUTATED_DRAFT\",\"pages\":[]}";db.update("update forms set definition=cast(? as jsonb) where id=?",changed,form);HttpHeaders h=new HttpHeaders();h.set("X-Respondent-Session",respondent);ResponseEntity<String> r=http.exchange(u("/sessions/"+session),HttpMethod.GET,new HttpEntity<>(h),String.class);assertEquals(HttpStatus.OK,r.getStatusCode());assertFalse(r.getBody().contains("MUTATED_DRAFT"));assertTrue(r.getBody().contains("4.0.0"));}
}
